/*
 * This file is generated by jOOQ.
*/
package com.paulliu.jooq.tables;


import com.paulliu.jooq.Indexes;
import com.paulliu.jooq.Keys;
import com.paulliu.jooq.Test;
import com.paulliu.jooq.tables.records.TBonuspackageInfoRecord;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 红包套餐属性表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TBonuspackageInfo extends TableImpl<TBonuspackageInfoRecord> {

    private static final long serialVersionUID = 908750669;

    /**
     * The reference instance of <code>test.T_BONUSPACKAGE_INFO</code>
     */
    public static final TBonuspackageInfo T_BONUSPACKAGE_INFO = new TBonuspackageInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TBonuspackageInfoRecord> getRecordType() {
        return TBonuspackageInfoRecord.class;
    }

    /**
     * The column <code>test.T_BONUSPACKAGE_INFO.ID</code>. 主键
     */
    public final TableField<TBonuspackageInfoRecord, Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "主键");

    /**
     * The column <code>test.T_BONUSPACKAGE_INFO.PRODUCT_NO</code>. 用户手机号
     */
    public final TableField<TBonuspackageInfoRecord, String> PRODUCT_NO = createField("PRODUCT_NO", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "用户手机号");

    /**
     * The column <code>test.T_BONUSPACKAGE_INFO.CONTRACT_NO</code>. 客户账户号
     */
    public final TableField<TBonuspackageInfoRecord, String> CONTRACT_NO = createField("CONTRACT_NO", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "客户账户号");

    /**
     * The column <code>test.T_BONUSPACKAGE_INFO.PROMPT_CODE</code>. 销售产品号
     */
    public final TableField<TBonuspackageInfoRecord, String> PROMPT_CODE = createField("PROMPT_CODE", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("default", org.jooq.impl.SQLDataType.VARCHAR)), this, "销售产品号");

    /**
     * The column <code>test.T_BONUSPACKAGE_INFO.PROTOCOL_VERSION</code>. 协议版本
     */
    public final TableField<TBonuspackageInfoRecord, String> PROTOCOL_VERSION = createField("PROTOCOL_VERSION", org.jooq.impl.SQLDataType.VARCHAR(32), this, "协议版本");

    /**
     * The column <code>test.T_BONUSPACKAGE_INFO.PROTOCOL_BEGIN_AT</code>. 协议生效日期
     */
    public final TableField<TBonuspackageInfoRecord, Date> PROTOCOL_BEGIN_AT = createField("PROTOCOL_BEGIN_AT", org.jooq.impl.SQLDataType.DATE, this, "协议生效日期");

    /**
     * The column <code>test.T_BONUSPACKAGE_INFO.PROTOCOL_END_AT</code>. 协议失效日期
     */
    public final TableField<TBonuspackageInfoRecord, Date> PROTOCOL_END_AT = createField("PROTOCOL_END_AT", org.jooq.impl.SQLDataType.DATE, this, "协议失效日期");

    /**
     * The column <code>test.T_BONUSPACKAGE_INFO.REBATE_CYCLE</code>. 返利期数
     */
    public final TableField<TBonuspackageInfoRecord, String> REBATE_CYCLE = createField("REBATE_CYCLE", org.jooq.impl.SQLDataType.VARCHAR(3), this, "返利期数");

    /**
     * The column <code>test.T_BONUSPACKAGE_INFO.FIRST_REBATE_AT</code>. 首次返利时间
     */
    public final TableField<TBonuspackageInfoRecord, Date> FIRST_REBATE_AT = createField("FIRST_REBATE_AT", org.jooq.impl.SQLDataType.DATE, this, "首次返利时间");

    /**
     * The column <code>test.T_BONUSPACKAGE_INFO.PROTOCOL_STATUS</code>. 状态：ENABLE-可用，DISABLE-不可用，DISCRAD-废弃
     */
    public final TableField<TBonuspackageInfoRecord, String> PROTOCOL_STATUS = createField("PROTOCOL_STATUS", org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false).defaultValue(org.jooq.impl.DSL.inline("ENABLE", org.jooq.impl.SQLDataType.VARCHAR)), this, "状态：ENABLE-可用，DISABLE-不可用，DISCRAD-废弃");

    /**
     * The column <code>test.T_BONUSPACKAGE_INFO.CREATED_AT</code>. 创建时间
     */
    public final TableField<TBonuspackageInfoRecord, Timestamp> CREATED_AT = createField("CREATED_AT", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");

    /**
     * The column <code>test.T_BONUSPACKAGE_INFO.CREATED_BY</code>. 创建用户
     */
    public final TableField<TBonuspackageInfoRecord, String> CREATED_BY = createField("CREATED_BY", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("system", org.jooq.impl.SQLDataType.VARCHAR)), this, "创建用户");

    /**
     * The column <code>test.T_BONUSPACKAGE_INFO.UPDATED_AT</code>. 更新时间
     */
    public final TableField<TBonuspackageInfoRecord, Timestamp> UPDATED_AT = createField("UPDATED_AT", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "更新时间");

    /**
     * The column <code>test.T_BONUSPACKAGE_INFO.UPDATED_BY</code>. 更新用户
     */
    public final TableField<TBonuspackageInfoRecord, String> UPDATED_BY = createField("UPDATED_BY", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("system", org.jooq.impl.SQLDataType.VARCHAR)), this, "更新用户");

    /**
     * Create a <code>test.T_BONUSPACKAGE_INFO</code> table reference
     */
    public TBonuspackageInfo() {
        this(DSL.name("T_BONUSPACKAGE_INFO"), null);
    }

    /**
     * Create an aliased <code>test.T_BONUSPACKAGE_INFO</code> table reference
     */
    public TBonuspackageInfo(String alias) {
        this(DSL.name(alias), T_BONUSPACKAGE_INFO);
    }

    /**
     * Create an aliased <code>test.T_BONUSPACKAGE_INFO</code> table reference
     */
    public TBonuspackageInfo(Name alias) {
        this(alias, T_BONUSPACKAGE_INFO);
    }

    private TBonuspackageInfo(Name alias, Table<TBonuspackageInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private TBonuspackageInfo(Name alias, Table<TBonuspackageInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "红包套餐属性表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Test.TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_BONUSPACKAGE_INFO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TBonuspackageInfoRecord, Long> getIdentity() {
        return Keys.IDENTITY_T_BONUSPACKAGE_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TBonuspackageInfoRecord> getPrimaryKey() {
        return Keys.KEY_T_BONUSPACKAGE_INFO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TBonuspackageInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<TBonuspackageInfoRecord>>asList(Keys.KEY_T_BONUSPACKAGE_INFO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBonuspackageInfo as(String alias) {
        return new TBonuspackageInfo(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBonuspackageInfo as(Name alias) {
        return new TBonuspackageInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TBonuspackageInfo rename(String name) {
        return new TBonuspackageInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TBonuspackageInfo rename(Name name) {
        return new TBonuspackageInfo(name, null);
    }
}
