/*
 * This file is generated by jOOQ.
*/
package com.paulliu.jooq.tables;


import com.paulliu.jooq.Indexes;
import com.paulliu.jooq.Keys;
import com.paulliu.jooq.Test;
import com.paulliu.jooq.tables.records.TDemoRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDemo extends TableImpl<TDemoRecord> {

    private static final long serialVersionUID = -776670953;

    /**
     * The reference instance of <code>test.t_demo</code>
     */
    public static final TDemo T_DEMO = new TDemo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TDemoRecord> getRecordType() {
        return TDemoRecord.class;
    }

    /**
     * The column <code>test.t_demo.id</code>.
     */
    public final TableField<TDemoRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>test.t_demo.name</code>.
     */
    public final TableField<TDemoRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>test.t_demo.age</code>.
     */
    public final TableField<TDemoRecord, Byte> AGE = createField("age", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>test.t_demo.money</code>.
     */
    public final TableField<TDemoRecord, BigDecimal> MONEY = createField("money", org.jooq.impl.SQLDataType.DECIMAL(10, 2).nullable(false), this, "");

    /**
     * The column <code>test.t_demo.catalog</code>.
     */
    public final TableField<TDemoRecord, String> CATALOG = createField("catalog", org.jooq.impl.SQLDataType.VARCHAR(32), this, "");

    /**
     * Create a <code>test.t_demo</code> table reference
     */
    public TDemo() {
        this(DSL.name("t_demo"), null);
    }

    /**
     * Create an aliased <code>test.t_demo</code> table reference
     */
    public TDemo(String alias) {
        this(DSL.name(alias), T_DEMO);
    }

    /**
     * Create an aliased <code>test.t_demo</code> table reference
     */
    public TDemo(Name alias) {
        this(alias, T_DEMO);
    }

    private TDemo(Name alias, Table<TDemoRecord> aliased) {
        this(alias, aliased, null);
    }

    private TDemo(Name alias, Table<TDemoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Test.TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_DEMO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TDemoRecord, Integer> getIdentity() {
        return Keys.IDENTITY_T_DEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TDemoRecord> getPrimaryKey() {
        return Keys.KEY_T_DEMO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TDemoRecord>> getKeys() {
        return Arrays.<UniqueKey<TDemoRecord>>asList(Keys.KEY_T_DEMO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDemo as(String alias) {
        return new TDemo(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TDemo as(Name alias) {
        return new TDemo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TDemo rename(String name) {
        return new TDemo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TDemo rename(Name name) {
        return new TDemo(name, null);
    }
}
