/*
 * This file is generated by jOOQ.
*/
package com.paulliu.jooq.tables;


import com.paulliu.jooq.Test;
import com.paulliu.jooq.tables.records.TFianceTempRecord;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TFianceTemp extends TableImpl<TFianceTempRecord> {

    private static final long serialVersionUID = -1416441215;

    /**
     * The reference instance of <code>test.t_fiance_temp</code>
     */
    public static final TFianceTemp T_FIANCE_TEMP = new TFianceTemp();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TFianceTempRecord> getRecordType() {
        return TFianceTempRecord.class;
    }

    /**
     * The column <code>test.t_fiance_temp.prod_offer_name</code>.
     */
    public final TableField<TFianceTempRecord, String> PROD_OFFER_NAME = createField("prod_offer_name", org.jooq.impl.SQLDataType.VARCHAR(60), this, "");

    /**
     * The column <code>test.t_fiance_temp.prod_offer_id</code>.
     */
    public final TableField<TFianceTempRecord, String> PROD_OFFER_ID = createField("prod_offer_id", org.jooq.impl.SQLDataType.VARCHAR(60), this, "");

    /**
     * The column <code>test.t_fiance_temp.finish_time</code>.
     */
    public final TableField<TFianceTempRecord, Timestamp> FINISH_TIME = createField("finish_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>test.t_fiance_temp.acc_nbr</code>.
     */
    public final TableField<TFianceTempRecord, String> ACC_NBR = createField("acc_nbr", org.jooq.impl.SQLDataType.VARCHAR(60), this, "");

    /**
     * The column <code>test.t_fiance_temp.cust_order_id</code>.
     */
    public final TableField<TFianceTempRecord, String> CUST_ORDER_ID = createField("cust_order_id", org.jooq.impl.SQLDataType.VARCHAR(60), this, "");

    /**
     * The column <code>test.t_fiance_temp.order_item_id</code>.
     */
    public final TableField<TFianceTempRecord, String> ORDER_ITEM_ID = createField("order_item_id", org.jooq.impl.SQLDataType.VARCHAR(60), this, "");

    /**
     * The column <code>test.t_fiance_temp.rn</code>.
     */
    public final TableField<TFianceTempRecord, Integer> RN = createField("rn", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>test.t_fiance_temp</code> table reference
     */
    public TFianceTemp() {
        this(DSL.name("t_fiance_temp"), null);
    }

    /**
     * Create an aliased <code>test.t_fiance_temp</code> table reference
     */
    public TFianceTemp(String alias) {
        this(DSL.name(alias), T_FIANCE_TEMP);
    }

    /**
     * Create an aliased <code>test.t_fiance_temp</code> table reference
     */
    public TFianceTemp(Name alias) {
        this(alias, T_FIANCE_TEMP);
    }

    private TFianceTemp(Name alias, Table<TFianceTempRecord> aliased) {
        this(alias, aliased, null);
    }

    private TFianceTemp(Name alias, Table<TFianceTempRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Test.TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFianceTemp as(String alias) {
        return new TFianceTemp(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TFianceTemp as(Name alias) {
        return new TFianceTemp(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TFianceTemp rename(String name) {
        return new TFianceTemp(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TFianceTemp rename(Name name) {
        return new TFianceTemp(name, null);
    }
}
