/*
 * This file is generated by jOOQ.
*/
package com.paulliu.jooq.tables;


import com.paulliu.jooq.Indexes;
import com.paulliu.jooq.Keys;
import com.paulliu.jooq.Test;
import com.paulliu.jooq.tables.records.TWithdrawOrder_201803Record;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 提现订单表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TWithdrawOrder_201803 extends TableImpl<TWithdrawOrder_201803Record> {

    private static final long serialVersionUID = -142371237;

    /**
     * The reference instance of <code>test.t_withdraw_order_201803</code>
     */
    public static final TWithdrawOrder_201803 T_WITHDRAW_ORDER_201803 = new TWithdrawOrder_201803();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TWithdrawOrder_201803Record> getRecordType() {
        return TWithdrawOrder_201803Record.class;
    }

    /**
     * The column <code>test.t_withdraw_order_201803.id</code>. 主键
     */
    public final TableField<TWithdrawOrder_201803Record, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "主键");

    /**
     * The column <code>test.t_withdraw_order_201803.request_order_no</code>. 请求系统单号
     */
    public final TableField<TWithdrawOrder_201803Record, String> REQUEST_ORDER_NO = createField("request_order_no", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "请求系统单号");

    /**
     * The column <code>test.t_withdraw_order_201803.withdraw_order_no</code>. 提现单号
     */
    public final TableField<TWithdrawOrder_201803Record, String> WITHDRAW_ORDER_NO = createField("withdraw_order_no", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "提现单号");

    /**
     * The column <code>test.t_withdraw_order_201803.trade_no</code>. 交易号
     */
    public final TableField<TWithdrawOrder_201803Record, String> TRADE_NO = createField("trade_no", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "交易号");

    /**
     * The column <code>test.t_withdraw_order_201803.trade_status</code>. 交易状态
     */
    public final TableField<TWithdrawOrder_201803Record, String> TRADE_STATUS = createField("trade_status", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "交易状态");

    /**
     * The column <code>test.t_withdraw_order_201803.trade_finished_date</code>. 交易完成时间
     */
    public final TableField<TWithdrawOrder_201803Record, Timestamp> TRADE_FINISHED_DATE = createField("trade_finished_date", org.jooq.impl.SQLDataType.TIMESTAMP, this, "交易完成时间");

    /**
     * The column <code>test.t_withdraw_order_201803.pay_amt</code>. 实际支付金额
     */
    public final TableField<TWithdrawOrder_201803Record, Long> PAY_AMT = createField("pay_amt", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "实际支付金额");

    /**
     * The column <code>test.t_withdraw_order_201803.discount_amt</code>. 优惠金额
     */
    public final TableField<TWithdrawOrder_201803Record, Long> DISCOUNT_AMT = createField("discount_amt", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "优惠金额");

    /**
     * The column <code>test.t_withdraw_order_201803.fee_amt</code>. 手续费金额
     */
    public final TableField<TWithdrawOrder_201803Record, Long> FEE_AMT = createField("fee_amt", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "手续费金额");

    /**
     * The column <code>test.t_withdraw_order_201803.request_system</code>. 请求系统
     */
    public final TableField<TWithdrawOrder_201803Record, String> REQUEST_SYSTEM = createField("request_system", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "请求系统");

    /**
     * The column <code>test.t_withdraw_order_201803.request_date</code>. 请求时间
     */
    public final TableField<TWithdrawOrder_201803Record, Timestamp> REQUEST_DATE = createField("request_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "请求时间");

    /**
     * The column <code>test.t_withdraw_order_201803.product_code</code>. 产品码
     */
    public final TableField<TWithdrawOrder_201803Record, String> PRODUCT_CODE = createField("product_code", org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false), this, "产品码");

    /**
     * The column <code>test.t_withdraw_order_201803.trade_channel</code>. 交易渠道
     */
    public final TableField<TWithdrawOrder_201803Record, String> TRADE_CHANNEL = createField("trade_channel", org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false), this, "交易渠道");

    /**
     * The column <code>test.t_withdraw_order_201803.customer_no</code>. 账号
     */
    public final TableField<TWithdrawOrder_201803Record, String> CUSTOMER_NO = createField("customer_no", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "账号");

    /**
     * The column <code>test.t_withdraw_order_201803.customer_type</code>. 客户类型 OPERATOR_NO-操作员号  MERCHANT_NO-商户号
     */
    public final TableField<TWithdrawOrder_201803Record, String> CUSTOMER_TYPE = createField("customer_type", org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false), this, "客户类型 OPERATOR_NO-操作员号  MERCHANT_NO-商户号");

    /**
     * The column <code>test.t_withdraw_order_201803.bank_card_no</code>. 银行卡号
     */
    public final TableField<TWithdrawOrder_201803Record, String> BANK_CARD_NO = createField("bank_card_no", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "银行卡号");

    /**
     * The column <code>test.t_withdraw_order_201803.mask_bank_card_no</code>. 银行卡号掩码
     */
    public final TableField<TWithdrawOrder_201803Record, String> MASK_BANK_CARD_NO = createField("mask_bank_card_no", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "银行卡号掩码");

    /**
     * The column <code>test.t_withdraw_order_201803.bank_org</code>. 银行机构-英文简称
     */
    public final TableField<TWithdrawOrder_201803Record, String> BANK_ORG = createField("bank_org", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "银行机构-英文简称");

    /**
     * The column <code>test.t_withdraw_order_201803.bank_name</code>. 银行名称-中文名称
     */
    public final TableField<TWithdrawOrder_201803Record, String> BANK_NAME = createField("bank_name", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "银行名称-中文名称");

    /**
     * The column <code>test.t_withdraw_order_201803.pub_pri_type</code>. 公私标识--PUBLIC:对公业务；PRIVATE：对私业务
     */
    public final TableField<TWithdrawOrder_201803Record, String> PUB_PRI_TYPE = createField("pub_pri_type", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "公私标识--PUBLIC:对公业务；PRIVATE：对私业务");

    /**
     * The column <code>test.t_withdraw_order_201803.customer_name</code>. 客户姓名
     */
    public final TableField<TWithdrawOrder_201803Record, String> CUSTOMER_NAME = createField("customer_name", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "客户姓名");

    /**
     * The column <code>test.t_withdraw_order_201803.card_type</code>. 卡类型--DEBIT：借记卡;CREDIT：贷记卡
     */
    public final TableField<TWithdrawOrder_201803Record, String> CARD_TYPE = createField("card_type", org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false), this, "卡类型--DEBIT：借记卡;CREDIT：贷记卡");

    /**
     * The column <code>test.t_withdraw_order_201803.amount</code>. 金额
     */
    public final TableField<TWithdrawOrder_201803Record, Integer> AMOUNT = createField("amount", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "金额");

    /**
     * The column <code>test.t_withdraw_order_201803.ccy</code>. 币种
     */
    public final TableField<TWithdrawOrder_201803Record, String> CCY = createField("ccy", org.jooq.impl.SQLDataType.VARCHAR(3).nullable(false), this, "币种");

    /**
     * The column <code>test.t_withdraw_order_201803.trans_reason</code>. 交易原因
     */
    public final TableField<TWithdrawOrder_201803Record, String> TRANS_REASON = createField("trans_reason", org.jooq.impl.SQLDataType.VARCHAR(256).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "交易原因");

    /**
     * The column <code>test.t_withdraw_order_201803.operator</code>. 操作人
     */
    public final TableField<TWithdrawOrder_201803Record, String> OPERATOR = createField("operator", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "操作人");

    /**
     * The column <code>test.t_withdraw_order_201803.memo</code>. 备注
     */
    public final TableField<TWithdrawOrder_201803Record, String> MEMO = createField("memo", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "备注");

    /**
     * The column <code>test.t_withdraw_order_201803.result_code</code>. 结果码
     */
    public final TableField<TWithdrawOrder_201803Record, String> RESULT_CODE = createField("result_code", org.jooq.impl.SQLDataType.VARCHAR(16).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "结果码");

    /**
     * The column <code>test.t_withdraw_order_201803.result_msg</code>. 结果消息
     */
    public final TableField<TWithdrawOrder_201803Record, String> RESULT_MSG = createField("result_msg", org.jooq.impl.SQLDataType.VARCHAR(256).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "结果消息");

    /**
     * The column <code>test.t_withdraw_order_201803.created_at</code>. 创建时间
     */
    public final TableField<TWithdrawOrder_201803Record, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");

    /**
     * The column <code>test.t_withdraw_order_201803.created_by</code>. 创建人
     */
    public final TableField<TWithdrawOrder_201803Record, String> CREATED_BY = createField("created_by", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "创建人");

    /**
     * The column <code>test.t_withdraw_order_201803.updated_at</code>. 修改时间
     */
    public final TableField<TWithdrawOrder_201803Record, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "修改时间");

    /**
     * The column <code>test.t_withdraw_order_201803.updated_by</code>. 修改人
     */
    public final TableField<TWithdrawOrder_201803Record, String> UPDATED_BY = createField("updated_by", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "修改人");

    /**
     * Create a <code>test.t_withdraw_order_201803</code> table reference
     */
    public TWithdrawOrder_201803() {
        this(DSL.name("t_withdraw_order_201803"), null);
    }

    /**
     * Create an aliased <code>test.t_withdraw_order_201803</code> table reference
     */
    public TWithdrawOrder_201803(String alias) {
        this(DSL.name(alias), T_WITHDRAW_ORDER_201803);
    }

    /**
     * Create an aliased <code>test.t_withdraw_order_201803</code> table reference
     */
    public TWithdrawOrder_201803(Name alias) {
        this(alias, T_WITHDRAW_ORDER_201803);
    }

    private TWithdrawOrder_201803(Name alias, Table<TWithdrawOrder_201803Record> aliased) {
        this(alias, aliased, null);
    }

    private TWithdrawOrder_201803(Name alias, Table<TWithdrawOrder_201803Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "提现订单表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Test.TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_WITHDRAW_ORDER_201803_IDX_MNO_RNO_RSY_PK, Indexes.T_WITHDRAW_ORDER_201803_IDX_TRADE_NO_PK, Indexes.T_WITHDRAW_ORDER_201803_IDX_WITHDRAW_ORDER_NO_PK, Indexes.T_WITHDRAW_ORDER_201803_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TWithdrawOrder_201803Record, Long> getIdentity() {
        return Keys.IDENTITY_T_WITHDRAW_ORDER_201803;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TWithdrawOrder_201803Record> getPrimaryKey() {
        return Keys.KEY_T_WITHDRAW_ORDER_201803_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TWithdrawOrder_201803Record>> getKeys() {
        return Arrays.<UniqueKey<TWithdrawOrder_201803Record>>asList(Keys.KEY_T_WITHDRAW_ORDER_201803_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWithdrawOrder_201803 as(String alias) {
        return new TWithdrawOrder_201803(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWithdrawOrder_201803 as(Name alias) {
        return new TWithdrawOrder_201803(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TWithdrawOrder_201803 rename(String name) {
        return new TWithdrawOrder_201803(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TWithdrawOrder_201803 rename(Name name) {
        return new TWithdrawOrder_201803(name, null);
    }
}
