/*
 * This file is generated by jOOQ.
*/
package com.paulliu.jooq.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 红包套餐属性表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITBonuspackageInfo extends VertxPojo, Serializable {

    /**
     * Setter for <code>test.T_BONUSPACKAGE_INFO.ID</code>. 主键
     */
    public ITBonuspackageInfo setId(Long value);

    /**
     * Getter for <code>test.T_BONUSPACKAGE_INFO.ID</code>. 主键
     */
    public Long getId();

    /**
     * Setter for <code>test.T_BONUSPACKAGE_INFO.PRODUCT_NO</code>. 用户手机号
     */
    public ITBonuspackageInfo setProductNo(String value);

    /**
     * Getter for <code>test.T_BONUSPACKAGE_INFO.PRODUCT_NO</code>. 用户手机号
     */
    public String getProductNo();

    /**
     * Setter for <code>test.T_BONUSPACKAGE_INFO.CONTRACT_NO</code>. 客户账户号
     */
    public ITBonuspackageInfo setContractNo(String value);

    /**
     * Getter for <code>test.T_BONUSPACKAGE_INFO.CONTRACT_NO</code>. 客户账户号
     */
    public String getContractNo();

    /**
     * Setter for <code>test.T_BONUSPACKAGE_INFO.PROMPT_CODE</code>. 销售产品号
     */
    public ITBonuspackageInfo setPromptCode(String value);

    /**
     * Getter for <code>test.T_BONUSPACKAGE_INFO.PROMPT_CODE</code>. 销售产品号
     */
    public String getPromptCode();

    /**
     * Setter for <code>test.T_BONUSPACKAGE_INFO.PROTOCOL_VERSION</code>. 协议版本
     */
    public ITBonuspackageInfo setProtocolVersion(String value);

    /**
     * Getter for <code>test.T_BONUSPACKAGE_INFO.PROTOCOL_VERSION</code>. 协议版本
     */
    public String getProtocolVersion();

    /**
     * Setter for <code>test.T_BONUSPACKAGE_INFO.PROTOCOL_BEGIN_AT</code>. 协议生效日期
     */
    public ITBonuspackageInfo setProtocolBeginAt(Date value);

    /**
     * Getter for <code>test.T_BONUSPACKAGE_INFO.PROTOCOL_BEGIN_AT</code>. 协议生效日期
     */
    public Date getProtocolBeginAt();

    /**
     * Setter for <code>test.T_BONUSPACKAGE_INFO.PROTOCOL_END_AT</code>. 协议失效日期
     */
    public ITBonuspackageInfo setProtocolEndAt(Date value);

    /**
     * Getter for <code>test.T_BONUSPACKAGE_INFO.PROTOCOL_END_AT</code>. 协议失效日期
     */
    public Date getProtocolEndAt();

    /**
     * Setter for <code>test.T_BONUSPACKAGE_INFO.REBATE_CYCLE</code>. 返利期数
     */
    public ITBonuspackageInfo setRebateCycle(String value);

    /**
     * Getter for <code>test.T_BONUSPACKAGE_INFO.REBATE_CYCLE</code>. 返利期数
     */
    public String getRebateCycle();

    /**
     * Setter for <code>test.T_BONUSPACKAGE_INFO.FIRST_REBATE_AT</code>. 首次返利时间
     */
    public ITBonuspackageInfo setFirstRebateAt(Date value);

    /**
     * Getter for <code>test.T_BONUSPACKAGE_INFO.FIRST_REBATE_AT</code>. 首次返利时间
     */
    public Date getFirstRebateAt();

    /**
     * Setter for <code>test.T_BONUSPACKAGE_INFO.PROTOCOL_STATUS</code>. 状态：ENABLE-可用，DISABLE-不可用，DISCRAD-废弃
     */
    public ITBonuspackageInfo setProtocolStatus(String value);

    /**
     * Getter for <code>test.T_BONUSPACKAGE_INFO.PROTOCOL_STATUS</code>. 状态：ENABLE-可用，DISABLE-不可用，DISCRAD-废弃
     */
    public String getProtocolStatus();

    /**
     * Setter for <code>test.T_BONUSPACKAGE_INFO.CREATED_AT</code>. 创建时间
     */
    public ITBonuspackageInfo setCreatedAt(Timestamp value);

    /**
     * Getter for <code>test.T_BONUSPACKAGE_INFO.CREATED_AT</code>. 创建时间
     */
    public Timestamp getCreatedAt();

    /**
     * Setter for <code>test.T_BONUSPACKAGE_INFO.CREATED_BY</code>. 创建用户
     */
    public ITBonuspackageInfo setCreatedBy(String value);

    /**
     * Getter for <code>test.T_BONUSPACKAGE_INFO.CREATED_BY</code>. 创建用户
     */
    public String getCreatedBy();

    /**
     * Setter for <code>test.T_BONUSPACKAGE_INFO.UPDATED_AT</code>. 更新时间
     */
    public ITBonuspackageInfo setUpdatedAt(Timestamp value);

    /**
     * Getter for <code>test.T_BONUSPACKAGE_INFO.UPDATED_AT</code>. 更新时间
     */
    public Timestamp getUpdatedAt();

    /**
     * Setter for <code>test.T_BONUSPACKAGE_INFO.UPDATED_BY</code>. 更新用户
     */
    public ITBonuspackageInfo setUpdatedBy(String value);

    /**
     * Getter for <code>test.T_BONUSPACKAGE_INFO.UPDATED_BY</code>. 更新用户
     */
    public String getUpdatedBy();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITBonuspackageInfo
     */
    public void from(com.paulliu.jooq.tables.interfaces.ITBonuspackageInfo from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITBonuspackageInfo
     */
    public <E extends com.paulliu.jooq.tables.interfaces.ITBonuspackageInfo> E into(E into);

    @Override
    public default ITBonuspackageInfo fromJson(io.vertx.core.json.JsonObject json) {
        setId(json.getLong("ID"));
        setProductNo(json.getString("PRODUCT_NO"));
        setContractNo(json.getString("CONTRACT_NO"));
        setPromptCode(json.getString("PROMPT_CODE"));
        setProtocolVersion(json.getString("PROTOCOL_VERSION"));
        // Omitting unrecognized type java.sql.Date for column PROTOCOL_BEGIN_AT!
        // Omitting unrecognized type java.sql.Date for column PROTOCOL_END_AT!
        setRebateCycle(json.getString("REBATE_CYCLE"));
        // Omitting unrecognized type java.sql.Date for column FIRST_REBATE_AT!
        setProtocolStatus(json.getString("PROTOCOL_STATUS"));
        // Omitting unrecognized type java.sql.Timestamp for column CREATED_AT!
        setCreatedBy(json.getString("CREATED_BY"));
        // Omitting unrecognized type java.sql.Timestamp for column UPDATED_AT!
        setUpdatedBy(json.getString("UPDATED_BY"));
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("ID",getId());
        json.put("PRODUCT_NO",getProductNo());
        json.put("CONTRACT_NO",getContractNo());
        json.put("PROMPT_CODE",getPromptCode());
        json.put("PROTOCOL_VERSION",getProtocolVersion());
        // Omitting unrecognized type java.sql.Date for column PROTOCOL_BEGIN_AT!
        // Omitting unrecognized type java.sql.Date for column PROTOCOL_END_AT!
        json.put("REBATE_CYCLE",getRebateCycle());
        // Omitting unrecognized type java.sql.Date for column FIRST_REBATE_AT!
        json.put("PROTOCOL_STATUS",getProtocolStatus());
        // Omitting unrecognized type java.sql.Timestamp for column CREATED_AT!
        json.put("CREATED_BY",getCreatedBy());
        // Omitting unrecognized type java.sql.Timestamp for column UPDATED_AT!
        json.put("UPDATED_BY",getUpdatedBy());
        return json;
    }

}
