/*
 * This file is generated by jOOQ.
*/
package com.paulliu.jooq.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 定时任务配置表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITCapitalJobConfig extends VertxPojo, Serializable {

    /**
     * Setter for <code>test.t_capital_job_config.id</code>. ID
     */
    public ITCapitalJobConfig setId(Long value);

    /**
     * Getter for <code>test.t_capital_job_config.id</code>. ID
     */
    public Long getId();

    /**
     * Setter for <code>test.t_capital_job_config.job_name</code>. 任务名称（类名或者bean名）
     */
    public ITCapitalJobConfig setJobName(String value);

    /**
     * Getter for <code>test.t_capital_job_config.job_name</code>. 任务名称（类名或者bean名）
     */
    public String getJobName();

    /**
     * Setter for <code>test.t_capital_job_config.job_env</code>. 任务运行环境:DEV:开发环境、TEST:综测环境、PRE_PRODUCE:准生产环境、PRODUCE:生产环境
     */
    public ITCapitalJobConfig setJobEnv(String value);

    /**
     * Getter for <code>test.t_capital_job_config.job_env</code>. 任务运行环境:DEV:开发环境、TEST:综测环境、PRE_PRODUCE:准生产环境、PRODUCE:生产环境
     */
    public String getJobEnv();

    /**
     * Setter for <code>test.t_capital_job_config.job_class</code>. 类名全路径
     */
    public ITCapitalJobConfig setJobClass(String value);

    /**
     * Getter for <code>test.t_capital_job_config.job_class</code>. 类名全路径
     */
    public String getJobClass();

    /**
     * Setter for <code>test.t_capital_job_config.status</code>. 状态:normal:有效
     */
    public ITCapitalJobConfig setStatus(String value);

    /**
     * Getter for <code>test.t_capital_job_config.status</code>. 状态:normal:有效
     */
    public String getStatus();

    /**
     * Setter for <code>test.t_capital_job_config.is_loading</code>. 运行状态：loading:待运行,running:正在运行
     */
    public ITCapitalJobConfig setIsLoading(String value);

    /**
     * Getter for <code>test.t_capital_job_config.is_loading</code>. 运行状态：loading:待运行,running:正在运行
     */
    public String getIsLoading();

    /**
     * Setter for <code>test.t_capital_job_config.sharding_total_count</code>. 分片总数
     */
    public ITCapitalJobConfig setShardingTotalCount(Long value);

    /**
     * Getter for <code>test.t_capital_job_config.sharding_total_count</code>. 分片总数
     */
    public Long getShardingTotalCount();

    /**
     * Setter for <code>test.t_capital_job_config.exec_count</code>. 单任务处理条数
     */
    public ITCapitalJobConfig setExecCount(Long value);

    /**
     * Getter for <code>test.t_capital_job_config.exec_count</code>. 单任务处理条数
     */
    public Long getExecCount();

    /**
     * Setter for <code>test.t_capital_job_config.job_desc</code>. 任务描述
     */
    public ITCapitalJobConfig setJobDesc(String value);

    /**
     * Getter for <code>test.t_capital_job_config.job_desc</code>. 任务描述
     */
    public String getJobDesc();

    /**
     * Setter for <code>test.t_capital_job_config.created_at</code>. 创建时间
     */
    public ITCapitalJobConfig setCreatedAt(Timestamp value);

    /**
     * Getter for <code>test.t_capital_job_config.created_at</code>. 创建时间
     */
    public Timestamp getCreatedAt();

    /**
     * Setter for <code>test.t_capital_job_config.created_by</code>. 创建人
     */
    public ITCapitalJobConfig setCreatedBy(String value);

    /**
     * Getter for <code>test.t_capital_job_config.created_by</code>. 创建人
     */
    public String getCreatedBy();

    /**
     * Setter for <code>test.t_capital_job_config.updated_at</code>. 修改时间
     */
    public ITCapitalJobConfig setUpdatedAt(Timestamp value);

    /**
     * Getter for <code>test.t_capital_job_config.updated_at</code>. 修改时间
     */
    public Timestamp getUpdatedAt();

    /**
     * Setter for <code>test.t_capital_job_config.updated_by</code>. 修改人
     */
    public ITCapitalJobConfig setUpdatedBy(String value);

    /**
     * Getter for <code>test.t_capital_job_config.updated_by</code>. 修改人
     */
    public String getUpdatedBy();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITCapitalJobConfig
     */
    public void from(com.paulliu.jooq.tables.interfaces.ITCapitalJobConfig from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITCapitalJobConfig
     */
    public <E extends com.paulliu.jooq.tables.interfaces.ITCapitalJobConfig> E into(E into);

    @Override
    public default ITCapitalJobConfig fromJson(io.vertx.core.json.JsonObject json) {
        setId(json.getLong("id"));
        setJobName(json.getString("job_name"));
        setJobEnv(json.getString("job_env"));
        setJobClass(json.getString("job_class"));
        setStatus(json.getString("status"));
        setIsLoading(json.getString("is_loading"));
        setShardingTotalCount(json.getLong("sharding_total_count"));
        setExecCount(json.getLong("exec_count"));
        setJobDesc(json.getString("job_desc"));
        // Omitting unrecognized type java.sql.Timestamp for column created_at!
        setCreatedBy(json.getString("created_by"));
        // Omitting unrecognized type java.sql.Timestamp for column updated_at!
        setUpdatedBy(json.getString("updated_by"));
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("id",getId());
        json.put("job_name",getJobName());
        json.put("job_env",getJobEnv());
        json.put("job_class",getJobClass());
        json.put("status",getStatus());
        json.put("is_loading",getIsLoading());
        json.put("sharding_total_count",getShardingTotalCount());
        json.put("exec_count",getExecCount());
        json.put("job_desc",getJobDesc());
        // Omitting unrecognized type java.sql.Timestamp for column created_at!
        json.put("created_by",getCreatedBy());
        // Omitting unrecognized type java.sql.Timestamp for column updated_at!
        json.put("updated_by",getUpdatedBy());
        return json;
    }

}
