/*
 * This file is generated by jOOQ.
*/
package com.paulliu.jooq.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITDemo extends VertxPojo, Serializable {

    /**
     * Setter for <code>test.t_demo.id</code>.
     */
    public ITDemo setId(Integer value);

    /**
     * Getter for <code>test.t_demo.id</code>.
     */
    public Integer getId();

    /**
     * Setter for <code>test.t_demo.name</code>.
     */
    public ITDemo setName(String value);

    /**
     * Getter for <code>test.t_demo.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>test.t_demo.age</code>.
     */
    public ITDemo setAge(Byte value);

    /**
     * Getter for <code>test.t_demo.age</code>.
     */
    public Byte getAge();

    /**
     * Setter for <code>test.t_demo.money</code>.
     */
    public ITDemo setMoney(BigDecimal value);

    /**
     * Getter for <code>test.t_demo.money</code>.
     */
    public BigDecimal getMoney();

    /**
     * Setter for <code>test.t_demo.catalog</code>.
     */
    public ITDemo setCatalog(String value);

    /**
     * Getter for <code>test.t_demo.catalog</code>.
     */
    public String getCatalog();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITDemo
     */
    public void from(com.paulliu.jooq.tables.interfaces.ITDemo from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITDemo
     */
    public <E extends com.paulliu.jooq.tables.interfaces.ITDemo> E into(E into);

    @Override
    public default ITDemo fromJson(io.vertx.core.json.JsonObject json) {
        setId(json.getInteger("id"));
        setName(json.getString("name"));
        setAge(json.getInteger("age")==null?null:json.getInteger("age").byteValue());
        // Omitting unrecognized type java.math.BigDecimal for column money!
        setCatalog(json.getString("catalog"));
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("id",getId());
        json.put("name",getName());
        json.put("age",getAge());
        // Omitting unrecognized type java.math.BigDecimal for column money!
        json.put("catalog",getCatalog());
        return json;
    }

}
