/*
 * This file is generated by jOOQ.
*/
package com.paulliu.jooq.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITOther extends VertxPojo, Serializable {

    /**
     * Setter for <code>test.t_other.id</code>.
     */
    public ITOther setId(Integer value);

    /**
     * Getter for <code>test.t_other.id</code>.
     */
    public Integer getId();

    /**
     * Setter for <code>test.t_other.other_name</code>.
     */
    public ITOther setOtherName(String value);

    /**
     * Getter for <code>test.t_other.other_name</code>.
     */
    public String getOtherName();

    /**
     * Setter for <code>test.t_other.other_thing</code>.
     */
    public ITOther setOtherThing(String value);

    /**
     * Getter for <code>test.t_other.other_thing</code>.
     */
    public String getOtherThing();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITOther
     */
    public void from(com.paulliu.jooq.tables.interfaces.ITOther from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITOther
     */
    public <E extends com.paulliu.jooq.tables.interfaces.ITOther> E into(E into);

    @Override
    public default ITOther fromJson(io.vertx.core.json.JsonObject json) {
        setId(json.getInteger("id"));
        setOtherName(json.getString("other_name"));
        setOtherThing(json.getString("other_thing"));
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("id",getId());
        json.put("other_name",getOtherName());
        json.put("other_thing",getOtherThing());
        return json;
    }

}
