/*
 * This file is generated by jOOQ.
*/
package com.paulliu.jooq.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 提现订单表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITWithdrawOrder_201803 extends VertxPojo, Serializable {

    /**
     * Setter for <code>test.t_withdraw_order_201803.id</code>. 主键
     */
    public ITWithdrawOrder_201803 setId(Long value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.id</code>. 主键
     */
    public Long getId();

    /**
     * Setter for <code>test.t_withdraw_order_201803.request_order_no</code>. 请求系统单号
     */
    public ITWithdrawOrder_201803 setRequestOrderNo(String value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.request_order_no</code>. 请求系统单号
     */
    public String getRequestOrderNo();

    /**
     * Setter for <code>test.t_withdraw_order_201803.withdraw_order_no</code>. 提现单号
     */
    public ITWithdrawOrder_201803 setWithdrawOrderNo(String value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.withdraw_order_no</code>. 提现单号
     */
    public String getWithdrawOrderNo();

    /**
     * Setter for <code>test.t_withdraw_order_201803.trade_no</code>. 交易号
     */
    public ITWithdrawOrder_201803 setTradeNo(String value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.trade_no</code>. 交易号
     */
    public String getTradeNo();

    /**
     * Setter for <code>test.t_withdraw_order_201803.trade_status</code>. 交易状态
     */
    public ITWithdrawOrder_201803 setTradeStatus(String value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.trade_status</code>. 交易状态
     */
    public String getTradeStatus();

    /**
     * Setter for <code>test.t_withdraw_order_201803.trade_finished_date</code>. 交易完成时间
     */
    public ITWithdrawOrder_201803 setTradeFinishedDate(Timestamp value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.trade_finished_date</code>. 交易完成时间
     */
    public Timestamp getTradeFinishedDate();

    /**
     * Setter for <code>test.t_withdraw_order_201803.pay_amt</code>. 实际支付金额
     */
    public ITWithdrawOrder_201803 setPayAmt(Long value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.pay_amt</code>. 实际支付金额
     */
    public Long getPayAmt();

    /**
     * Setter for <code>test.t_withdraw_order_201803.discount_amt</code>. 优惠金额
     */
    public ITWithdrawOrder_201803 setDiscountAmt(Long value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.discount_amt</code>. 优惠金额
     */
    public Long getDiscountAmt();

    /**
     * Setter for <code>test.t_withdraw_order_201803.fee_amt</code>. 手续费金额
     */
    public ITWithdrawOrder_201803 setFeeAmt(Long value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.fee_amt</code>. 手续费金额
     */
    public Long getFeeAmt();

    /**
     * Setter for <code>test.t_withdraw_order_201803.request_system</code>. 请求系统
     */
    public ITWithdrawOrder_201803 setRequestSystem(String value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.request_system</code>. 请求系统
     */
    public String getRequestSystem();

    /**
     * Setter for <code>test.t_withdraw_order_201803.request_date</code>. 请求时间
     */
    public ITWithdrawOrder_201803 setRequestDate(Timestamp value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.request_date</code>. 请求时间
     */
    public Timestamp getRequestDate();

    /**
     * Setter for <code>test.t_withdraw_order_201803.product_code</code>. 产品码
     */
    public ITWithdrawOrder_201803 setProductCode(String value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.product_code</code>. 产品码
     */
    public String getProductCode();

    /**
     * Setter for <code>test.t_withdraw_order_201803.trade_channel</code>. 交易渠道
     */
    public ITWithdrawOrder_201803 setTradeChannel(String value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.trade_channel</code>. 交易渠道
     */
    public String getTradeChannel();

    /**
     * Setter for <code>test.t_withdraw_order_201803.customer_no</code>. 账号
     */
    public ITWithdrawOrder_201803 setCustomerNo(String value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.customer_no</code>. 账号
     */
    public String getCustomerNo();

    /**
     * Setter for <code>test.t_withdraw_order_201803.customer_type</code>. 客户类型 OPERATOR_NO-操作员号  MERCHANT_NO-商户号
     */
    public ITWithdrawOrder_201803 setCustomerType(String value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.customer_type</code>. 客户类型 OPERATOR_NO-操作员号  MERCHANT_NO-商户号
     */
    public String getCustomerType();

    /**
     * Setter for <code>test.t_withdraw_order_201803.bank_card_no</code>. 银行卡号
     */
    public ITWithdrawOrder_201803 setBankCardNo(String value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.bank_card_no</code>. 银行卡号
     */
    public String getBankCardNo();

    /**
     * Setter for <code>test.t_withdraw_order_201803.mask_bank_card_no</code>. 银行卡号掩码
     */
    public ITWithdrawOrder_201803 setMaskBankCardNo(String value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.mask_bank_card_no</code>. 银行卡号掩码
     */
    public String getMaskBankCardNo();

    /**
     * Setter for <code>test.t_withdraw_order_201803.bank_org</code>. 银行机构-英文简称
     */
    public ITWithdrawOrder_201803 setBankOrg(String value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.bank_org</code>. 银行机构-英文简称
     */
    public String getBankOrg();

    /**
     * Setter for <code>test.t_withdraw_order_201803.bank_name</code>. 银行名称-中文名称
     */
    public ITWithdrawOrder_201803 setBankName(String value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.bank_name</code>. 银行名称-中文名称
     */
    public String getBankName();

    /**
     * Setter for <code>test.t_withdraw_order_201803.pub_pri_type</code>. 公私标识--PUBLIC:对公业务；PRIVATE：对私业务
     */
    public ITWithdrawOrder_201803 setPubPriType(String value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.pub_pri_type</code>. 公私标识--PUBLIC:对公业务；PRIVATE：对私业务
     */
    public String getPubPriType();

    /**
     * Setter for <code>test.t_withdraw_order_201803.customer_name</code>. 客户姓名
     */
    public ITWithdrawOrder_201803 setCustomerName(String value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.customer_name</code>. 客户姓名
     */
    public String getCustomerName();

    /**
     * Setter for <code>test.t_withdraw_order_201803.card_type</code>. 卡类型--DEBIT：借记卡;CREDIT：贷记卡
     */
    public ITWithdrawOrder_201803 setCardType(String value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.card_type</code>. 卡类型--DEBIT：借记卡;CREDIT：贷记卡
     */
    public String getCardType();

    /**
     * Setter for <code>test.t_withdraw_order_201803.amount</code>. 金额
     */
    public ITWithdrawOrder_201803 setAmount(Integer value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.amount</code>. 金额
     */
    public Integer getAmount();

    /**
     * Setter for <code>test.t_withdraw_order_201803.ccy</code>. 币种
     */
    public ITWithdrawOrder_201803 setCcy(String value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.ccy</code>. 币种
     */
    public String getCcy();

    /**
     * Setter for <code>test.t_withdraw_order_201803.trans_reason</code>. 交易原因
     */
    public ITWithdrawOrder_201803 setTransReason(String value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.trans_reason</code>. 交易原因
     */
    public String getTransReason();

    /**
     * Setter for <code>test.t_withdraw_order_201803.operator</code>. 操作人
     */
    public ITWithdrawOrder_201803 setOperator(String value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.operator</code>. 操作人
     */
    public String getOperator();

    /**
     * Setter for <code>test.t_withdraw_order_201803.memo</code>. 备注
     */
    public ITWithdrawOrder_201803 setMemo(String value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.memo</code>. 备注
     */
    public String getMemo();

    /**
     * Setter for <code>test.t_withdraw_order_201803.result_code</code>. 结果码
     */
    public ITWithdrawOrder_201803 setResultCode(String value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.result_code</code>. 结果码
     */
    public String getResultCode();

    /**
     * Setter for <code>test.t_withdraw_order_201803.result_msg</code>. 结果消息
     */
    public ITWithdrawOrder_201803 setResultMsg(String value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.result_msg</code>. 结果消息
     */
    public String getResultMsg();

    /**
     * Setter for <code>test.t_withdraw_order_201803.created_at</code>. 创建时间
     */
    public ITWithdrawOrder_201803 setCreatedAt(Timestamp value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.created_at</code>. 创建时间
     */
    public Timestamp getCreatedAt();

    /**
     * Setter for <code>test.t_withdraw_order_201803.created_by</code>. 创建人
     */
    public ITWithdrawOrder_201803 setCreatedBy(String value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.created_by</code>. 创建人
     */
    public String getCreatedBy();

    /**
     * Setter for <code>test.t_withdraw_order_201803.updated_at</code>. 修改时间
     */
    public ITWithdrawOrder_201803 setUpdatedAt(Timestamp value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.updated_at</code>. 修改时间
     */
    public Timestamp getUpdatedAt();

    /**
     * Setter for <code>test.t_withdraw_order_201803.updated_by</code>. 修改人
     */
    public ITWithdrawOrder_201803 setUpdatedBy(String value);

    /**
     * Getter for <code>test.t_withdraw_order_201803.updated_by</code>. 修改人
     */
    public String getUpdatedBy();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITWithdrawOrder_201803
     */
    public void from(com.paulliu.jooq.tables.interfaces.ITWithdrawOrder_201803 from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITWithdrawOrder_201803
     */
    public <E extends com.paulliu.jooq.tables.interfaces.ITWithdrawOrder_201803> E into(E into);

    @Override
    public default ITWithdrawOrder_201803 fromJson(io.vertx.core.json.JsonObject json) {
        setId(json.getLong("id"));
        setRequestOrderNo(json.getString("request_order_no"));
        setWithdrawOrderNo(json.getString("withdraw_order_no"));
        setTradeNo(json.getString("trade_no"));
        setTradeStatus(json.getString("trade_status"));
        // Omitting unrecognized type java.sql.Timestamp for column trade_finished_date!
        setPayAmt(json.getLong("pay_amt"));
        setDiscountAmt(json.getLong("discount_amt"));
        setFeeAmt(json.getLong("fee_amt"));
        setRequestSystem(json.getString("request_system"));
        // Omitting unrecognized type java.sql.Timestamp for column request_date!
        setProductCode(json.getString("product_code"));
        setTradeChannel(json.getString("trade_channel"));
        setCustomerNo(json.getString("customer_no"));
        setCustomerType(json.getString("customer_type"));
        setBankCardNo(json.getString("bank_card_no"));
        setMaskBankCardNo(json.getString("mask_bank_card_no"));
        setBankOrg(json.getString("bank_org"));
        setBankName(json.getString("bank_name"));
        setPubPriType(json.getString("pub_pri_type"));
        setCustomerName(json.getString("customer_name"));
        setCardType(json.getString("card_type"));
        setAmount(json.getInteger("amount"));
        setCcy(json.getString("ccy"));
        setTransReason(json.getString("trans_reason"));
        setOperator(json.getString("operator"));
        setMemo(json.getString("memo"));
        setResultCode(json.getString("result_code"));
        setResultMsg(json.getString("result_msg"));
        // Omitting unrecognized type java.sql.Timestamp for column created_at!
        setCreatedBy(json.getString("created_by"));
        // Omitting unrecognized type java.sql.Timestamp for column updated_at!
        setUpdatedBy(json.getString("updated_by"));
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("id",getId());
        json.put("request_order_no",getRequestOrderNo());
        json.put("withdraw_order_no",getWithdrawOrderNo());
        json.put("trade_no",getTradeNo());
        json.put("trade_status",getTradeStatus());
        // Omitting unrecognized type java.sql.Timestamp for column trade_finished_date!
        json.put("pay_amt",getPayAmt());
        json.put("discount_amt",getDiscountAmt());
        json.put("fee_amt",getFeeAmt());
        json.put("request_system",getRequestSystem());
        // Omitting unrecognized type java.sql.Timestamp for column request_date!
        json.put("product_code",getProductCode());
        json.put("trade_channel",getTradeChannel());
        json.put("customer_no",getCustomerNo());
        json.put("customer_type",getCustomerType());
        json.put("bank_card_no",getBankCardNo());
        json.put("mask_bank_card_no",getMaskBankCardNo());
        json.put("bank_org",getBankOrg());
        json.put("bank_name",getBankName());
        json.put("pub_pri_type",getPubPriType());
        json.put("customer_name",getCustomerName());
        json.put("card_type",getCardType());
        json.put("amount",getAmount());
        json.put("ccy",getCcy());
        json.put("trans_reason",getTransReason());
        json.put("operator",getOperator());
        json.put("memo",getMemo());
        json.put("result_code",getResultCode());
        json.put("result_msg",getResultMsg());
        // Omitting unrecognized type java.sql.Timestamp for column created_at!
        json.put("created_by",getCreatedBy());
        // Omitting unrecognized type java.sql.Timestamp for column updated_at!
        json.put("updated_by",getUpdatedBy());
        return json;
    }

}
