/*
 * This file is generated by jOOQ.
*/
package com.paulliu.jooq.tables.daos;


import com.paulliu.jooq.tables.TCapitalJobConfig;
import com.paulliu.jooq.tables.records.TCapitalJobConfigRecord;

import io.github.jklingsporn.vertx.jooq.shared.internal.async.AbstractAsyncVertxDAO;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;


import io.reactivex.Completable;
import io.reactivex.Observable;
import io.reactivex.Single;
import java.util.Optional;
import io.github.jklingsporn.vertx.jooq.rx.async.AsyncRXQueryExecutor;
/**
 * 定时任务配置表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TCapitalJobConfigDao extends AbstractAsyncVertxDAO<TCapitalJobConfigRecord, com.paulliu.jooq.tables.pojos.TCapitalJobConfig, Long, Single<List<com.paulliu.jooq.tables.pojos.TCapitalJobConfig>>, Single<Optional<com.paulliu.jooq.tables.pojos.TCapitalJobConfig>>, Single<Integer>, Single<Long>> implements io.github.jklingsporn.vertx.jooq.rx.VertxDAO<TCapitalJobConfigRecord,com.paulliu.jooq.tables.pojos.TCapitalJobConfig,Long> {

    /**
     * @param configuration Used for rendering, so only SQLDialect must be set and must be one of the MYSQL types or POSTGRES.
     * @param delegate A configured AsyncSQLClient that is used for query execution
     */
    public TCapitalJobConfigDao(Configuration configuration,io.vertx.reactivex.ext.asyncsql.AsyncSQLClient delegate) {
        super(TCapitalJobConfig.T_CAPITAL_JOB_CONFIG, com.paulliu.jooq.tables.pojos.TCapitalJobConfig.class, new AsyncRXQueryExecutor<TCapitalJobConfigRecord,com.paulliu.jooq.tables.pojos.TCapitalJobConfig,Long>(delegate,com.paulliu.jooq.tables.pojos.TCapitalJobConfig::new, TCapitalJobConfig.T_CAPITAL_JOB_CONFIG), configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.paulliu.jooq.tables.pojos.TCapitalJobConfig object) {
        return object.getId();
    }

    /**
     * Find records that have <code>job_name IN (values)</code> asynchronously
     */
    public Single<List<com.paulliu.jooq.tables.pojos.TCapitalJobConfig>> findManyByJobName(List<String> values) {
        return findManyByCondition(TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.JOB_NAME.in(values));
    }

    /**
     * Find records that have <code>job_env IN (values)</code> asynchronously
     */
    public Single<List<com.paulliu.jooq.tables.pojos.TCapitalJobConfig>> findManyByJobEnv(List<String> values) {
        return findManyByCondition(TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.JOB_ENV.in(values));
    }

    /**
     * Find records that have <code>job_class IN (values)</code> asynchronously
     */
    public Single<List<com.paulliu.jooq.tables.pojos.TCapitalJobConfig>> findManyByJobClass(List<String> values) {
        return findManyByCondition(TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.JOB_CLASS.in(values));
    }

    /**
     * Find records that have <code>status IN (values)</code> asynchronously
     */
    public Single<List<com.paulliu.jooq.tables.pojos.TCapitalJobConfig>> findManyByStatus(List<String> values) {
        return findManyByCondition(TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.STATUS.in(values));
    }

    /**
     * Find records that have <code>is_loading IN (values)</code> asynchronously
     */
    public Single<List<com.paulliu.jooq.tables.pojos.TCapitalJobConfig>> findManyByIsLoading(List<String> values) {
        return findManyByCondition(TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.IS_LOADING.in(values));
    }

    /**
     * Find records that have <code>sharding_total_count IN (values)</code> asynchronously
     */
    public Single<List<com.paulliu.jooq.tables.pojos.TCapitalJobConfig>> findManyByShardingTotalCount(List<Long> values) {
        return findManyByCondition(TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.SHARDING_TOTAL_COUNT.in(values));
    }

    /**
     * Find records that have <code>exec_count IN (values)</code> asynchronously
     */
    public Single<List<com.paulliu.jooq.tables.pojos.TCapitalJobConfig>> findManyByExecCount(List<Long> values) {
        return findManyByCondition(TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.EXEC_COUNT.in(values));
    }

    /**
     * Find records that have <code>job_desc IN (values)</code> asynchronously
     */
    public Single<List<com.paulliu.jooq.tables.pojos.TCapitalJobConfig>> findManyByJobDesc(List<String> values) {
        return findManyByCondition(TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.JOB_DESC.in(values));
    }

    /**
     * Find records that have <code>created_at IN (values)</code> asynchronously
     */
    public Single<List<com.paulliu.jooq.tables.pojos.TCapitalJobConfig>> findManyByCreatedAt(List<Timestamp> values) {
        return findManyByCondition(TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.CREATED_AT.in(values));
    }

    /**
     * Find records that have <code>created_by IN (values)</code> asynchronously
     */
    public Single<List<com.paulliu.jooq.tables.pojos.TCapitalJobConfig>> findManyByCreatedBy(List<String> values) {
        return findManyByCondition(TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.CREATED_BY.in(values));
    }

    /**
     * Find records that have <code>updated_at IN (values)</code> asynchronously
     */
    public Single<List<com.paulliu.jooq.tables.pojos.TCapitalJobConfig>> findManyByUpdatedAt(List<Timestamp> values) {
        return findManyByCondition(TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.UPDATED_AT.in(values));
    }

    /**
     * Find records that have <code>updated_by IN (values)</code> asynchronously
     */
    public Single<List<com.paulliu.jooq.tables.pojos.TCapitalJobConfig>> findManyByUpdatedBy(List<String> values) {
        return findManyByCondition(TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.UPDATED_BY.in(values));
    }

    @Override
    protected java.util.function.Function<Object,Long> keyConverter(){
        return lastId -> Long.valueOf(((Long)lastId).longValue());
    }
}
