/*
 * This file is generated by jOOQ.
*/
package com.paulliu.jooq.tables.daos;


import com.paulliu.jooq.tables.TDemo;
import com.paulliu.jooq.tables.records.TDemoRecord;

import io.github.jklingsporn.vertx.jooq.shared.internal.async.AbstractAsyncVertxDAO;

import java.math.BigDecimal;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;


import io.reactivex.Completable;
import io.reactivex.Observable;
import io.reactivex.Single;
import java.util.Optional;
import io.github.jklingsporn.vertx.jooq.rx.async.AsyncRXQueryExecutor;
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDemoDao extends AbstractAsyncVertxDAO<TDemoRecord, com.paulliu.jooq.tables.pojos.TDemo, Integer, Single<List<com.paulliu.jooq.tables.pojos.TDemo>>, Single<Optional<com.paulliu.jooq.tables.pojos.TDemo>>, Single<Integer>, Single<Integer>> implements io.github.jklingsporn.vertx.jooq.rx.VertxDAO<TDemoRecord,com.paulliu.jooq.tables.pojos.TDemo,Integer> {

    /**
     * @param configuration Used for rendering, so only SQLDialect must be set and must be one of the MYSQL types or POSTGRES.
     * @param delegate A configured AsyncSQLClient that is used for query execution
     */
    public TDemoDao(Configuration configuration,io.vertx.reactivex.ext.asyncsql.AsyncSQLClient delegate) {
        super(TDemo.T_DEMO, com.paulliu.jooq.tables.pojos.TDemo.class, new AsyncRXQueryExecutor<TDemoRecord,com.paulliu.jooq.tables.pojos.TDemo,Integer>(delegate,com.paulliu.jooq.tables.pojos.TDemo::new, TDemo.T_DEMO), configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.paulliu.jooq.tables.pojos.TDemo object) {
        return object.getId();
    }

    /**
     * Find records that have <code>name IN (values)</code> asynchronously
     */
    public Single<List<com.paulliu.jooq.tables.pojos.TDemo>> findManyByName(List<String> values) {
        return findManyByCondition(TDemo.T_DEMO.NAME.in(values));
    }

    /**
     * Find records that have <code>age IN (values)</code> asynchronously
     */
    public Single<List<com.paulliu.jooq.tables.pojos.TDemo>> findManyByAge(List<Byte> values) {
        return findManyByCondition(TDemo.T_DEMO.AGE.in(values));
    }

    /**
     * Find records that have <code>money IN (values)</code> asynchronously
     */
    public Single<List<com.paulliu.jooq.tables.pojos.TDemo>> findManyByMoney(List<BigDecimal> values) {
        return findManyByCondition(TDemo.T_DEMO.MONEY.in(values));
    }

    /**
     * Find records that have <code>catalog IN (values)</code> asynchronously
     */
    public Single<List<com.paulliu.jooq.tables.pojos.TDemo>> findManyByCatalog(List<String> values) {
        return findManyByCondition(TDemo.T_DEMO.CATALOG.in(values));
    }

    @Override
    protected java.util.function.Function<Object,Integer> keyConverter(){
        return lastId -> Integer.valueOf(((Long)lastId).intValue());
    }
}
