/*
 * This file is generated by jOOQ.
*/
package com.paulliu.jooq.tables.pojos;


import com.paulliu.jooq.tables.interfaces.ITBonuspackageInfo;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 红包套餐属性表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TBonuspackageInfo implements ITBonuspackageInfo {

    private static final long serialVersionUID = -301057081;

    private Long      id;
    private String    productNo;
    private String    contractNo;
    private String    promptCode;
    private String    protocolVersion;
    private Date      protocolBeginAt;
    private Date      protocolEndAt;
    private String    rebateCycle;
    private Date      firstRebateAt;
    private String    protocolStatus;
    private Timestamp createdAt;
    private String    createdBy;
    private Timestamp updatedAt;
    private String    updatedBy;

    public TBonuspackageInfo() {}

    public TBonuspackageInfo(TBonuspackageInfo value) {
        this.id = value.id;
        this.productNo = value.productNo;
        this.contractNo = value.contractNo;
        this.promptCode = value.promptCode;
        this.protocolVersion = value.protocolVersion;
        this.protocolBeginAt = value.protocolBeginAt;
        this.protocolEndAt = value.protocolEndAt;
        this.rebateCycle = value.rebateCycle;
        this.firstRebateAt = value.firstRebateAt;
        this.protocolStatus = value.protocolStatus;
        this.createdAt = value.createdAt;
        this.createdBy = value.createdBy;
        this.updatedAt = value.updatedAt;
        this.updatedBy = value.updatedBy;
    }

    public TBonuspackageInfo(
        Long      id,
        String    productNo,
        String    contractNo,
        String    promptCode,
        String    protocolVersion,
        Date      protocolBeginAt,
        Date      protocolEndAt,
        String    rebateCycle,
        Date      firstRebateAt,
        String    protocolStatus,
        Timestamp createdAt,
        String    createdBy,
        Timestamp updatedAt,
        String    updatedBy
    ) {
        this.id = id;
        this.productNo = productNo;
        this.contractNo = contractNo;
        this.promptCode = promptCode;
        this.protocolVersion = protocolVersion;
        this.protocolBeginAt = protocolBeginAt;
        this.protocolEndAt = protocolEndAt;
        this.rebateCycle = rebateCycle;
        this.firstRebateAt = firstRebateAt;
        this.protocolStatus = protocolStatus;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
        this.updatedAt = updatedAt;
        this.updatedBy = updatedBy;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public TBonuspackageInfo setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public String getProductNo() {
        return this.productNo;
    }

    @Override
    public TBonuspackageInfo setProductNo(String productNo) {
        this.productNo = productNo;
        return this;
    }

    @Override
    public String getContractNo() {
        return this.contractNo;
    }

    @Override
    public TBonuspackageInfo setContractNo(String contractNo) {
        this.contractNo = contractNo;
        return this;
    }

    @Override
    public String getPromptCode() {
        return this.promptCode;
    }

    @Override
    public TBonuspackageInfo setPromptCode(String promptCode) {
        this.promptCode = promptCode;
        return this;
    }

    @Override
    public String getProtocolVersion() {
        return this.protocolVersion;
    }

    @Override
    public TBonuspackageInfo setProtocolVersion(String protocolVersion) {
        this.protocolVersion = protocolVersion;
        return this;
    }

    @Override
    public Date getProtocolBeginAt() {
        return this.protocolBeginAt;
    }

    @Override
    public TBonuspackageInfo setProtocolBeginAt(Date protocolBeginAt) {
        this.protocolBeginAt = protocolBeginAt;
        return this;
    }

    @Override
    public Date getProtocolEndAt() {
        return this.protocolEndAt;
    }

    @Override
    public TBonuspackageInfo setProtocolEndAt(Date protocolEndAt) {
        this.protocolEndAt = protocolEndAt;
        return this;
    }

    @Override
    public String getRebateCycle() {
        return this.rebateCycle;
    }

    @Override
    public TBonuspackageInfo setRebateCycle(String rebateCycle) {
        this.rebateCycle = rebateCycle;
        return this;
    }

    @Override
    public Date getFirstRebateAt() {
        return this.firstRebateAt;
    }

    @Override
    public TBonuspackageInfo setFirstRebateAt(Date firstRebateAt) {
        this.firstRebateAt = firstRebateAt;
        return this;
    }

    @Override
    public String getProtocolStatus() {
        return this.protocolStatus;
    }

    @Override
    public TBonuspackageInfo setProtocolStatus(String protocolStatus) {
        this.protocolStatus = protocolStatus;
        return this;
    }

    @Override
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public TBonuspackageInfo setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public String getCreatedBy() {
        return this.createdBy;
    }

    @Override
    public TBonuspackageInfo setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    @Override
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    @Override
    public TBonuspackageInfo setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    @Override
    public TBonuspackageInfo setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TBonuspackageInfo (");

        sb.append(id);
        sb.append(", ").append(productNo);
        sb.append(", ").append(contractNo);
        sb.append(", ").append(promptCode);
        sb.append(", ").append(protocolVersion);
        sb.append(", ").append(protocolBeginAt);
        sb.append(", ").append(protocolEndAt);
        sb.append(", ").append(rebateCycle);
        sb.append(", ").append(firstRebateAt);
        sb.append(", ").append(protocolStatus);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(updatedBy);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITBonuspackageInfo from) {
        setId(from.getId());
        setProductNo(from.getProductNo());
        setContractNo(from.getContractNo());
        setPromptCode(from.getPromptCode());
        setProtocolVersion(from.getProtocolVersion());
        setProtocolBeginAt(from.getProtocolBeginAt());
        setProtocolEndAt(from.getProtocolEndAt());
        setRebateCycle(from.getRebateCycle());
        setFirstRebateAt(from.getFirstRebateAt());
        setProtocolStatus(from.getProtocolStatus());
        setCreatedAt(from.getCreatedAt());
        setCreatedBy(from.getCreatedBy());
        setUpdatedAt(from.getUpdatedAt());
        setUpdatedBy(from.getUpdatedBy());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITBonuspackageInfo> E into(E into) {
        into.from(this);
        return into;
    }

    public TBonuspackageInfo(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
