/*
 * This file is generated by jOOQ.
*/
package com.paulliu.jooq.tables.pojos;


import com.paulliu.jooq.tables.interfaces.ITCapitalJobLog;

import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 定时任务日志表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TCapitalJobLog implements ITCapitalJobLog {

    private static final long serialVersionUID = 723678186;

    private Long      id;
    private Long      jobId;
    private String    jobName;
    private String    machineIp;
    private String    status;
    private String    errorMsg;
    private Timestamp startDate;
    private Timestamp endDate;
    private Long      shardingItem;
    private Long      execCount;
    private Timestamp createdAt;
    private String    createdBy;
    private Timestamp updatedAt;
    private String    updatedBy;

    public TCapitalJobLog() {}

    public TCapitalJobLog(TCapitalJobLog value) {
        this.id = value.id;
        this.jobId = value.jobId;
        this.jobName = value.jobName;
        this.machineIp = value.machineIp;
        this.status = value.status;
        this.errorMsg = value.errorMsg;
        this.startDate = value.startDate;
        this.endDate = value.endDate;
        this.shardingItem = value.shardingItem;
        this.execCount = value.execCount;
        this.createdAt = value.createdAt;
        this.createdBy = value.createdBy;
        this.updatedAt = value.updatedAt;
        this.updatedBy = value.updatedBy;
    }

    public TCapitalJobLog(
        Long      id,
        Long      jobId,
        String    jobName,
        String    machineIp,
        String    status,
        String    errorMsg,
        Timestamp startDate,
        Timestamp endDate,
        Long      shardingItem,
        Long      execCount,
        Timestamp createdAt,
        String    createdBy,
        Timestamp updatedAt,
        String    updatedBy
    ) {
        this.id = id;
        this.jobId = jobId;
        this.jobName = jobName;
        this.machineIp = machineIp;
        this.status = status;
        this.errorMsg = errorMsg;
        this.startDate = startDate;
        this.endDate = endDate;
        this.shardingItem = shardingItem;
        this.execCount = execCount;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
        this.updatedAt = updatedAt;
        this.updatedBy = updatedBy;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public TCapitalJobLog setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public Long getJobId() {
        return this.jobId;
    }

    @Override
    public TCapitalJobLog setJobId(Long jobId) {
        this.jobId = jobId;
        return this;
    }

    @Override
    public String getJobName() {
        return this.jobName;
    }

    @Override
    public TCapitalJobLog setJobName(String jobName) {
        this.jobName = jobName;
        return this;
    }

    @Override
    public String getMachineIp() {
        return this.machineIp;
    }

    @Override
    public TCapitalJobLog setMachineIp(String machineIp) {
        this.machineIp = machineIp;
        return this;
    }

    @Override
    public String getStatus() {
        return this.status;
    }

    @Override
    public TCapitalJobLog setStatus(String status) {
        this.status = status;
        return this;
    }

    @Override
    public String getErrorMsg() {
        return this.errorMsg;
    }

    @Override
    public TCapitalJobLog setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg;
        return this;
    }

    @Override
    public Timestamp getStartDate() {
        return this.startDate;
    }

    @Override
    public TCapitalJobLog setStartDate(Timestamp startDate) {
        this.startDate = startDate;
        return this;
    }

    @Override
    public Timestamp getEndDate() {
        return this.endDate;
    }

    @Override
    public TCapitalJobLog setEndDate(Timestamp endDate) {
        this.endDate = endDate;
        return this;
    }

    @Override
    public Long getShardingItem() {
        return this.shardingItem;
    }

    @Override
    public TCapitalJobLog setShardingItem(Long shardingItem) {
        this.shardingItem = shardingItem;
        return this;
    }

    @Override
    public Long getExecCount() {
        return this.execCount;
    }

    @Override
    public TCapitalJobLog setExecCount(Long execCount) {
        this.execCount = execCount;
        return this;
    }

    @Override
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public TCapitalJobLog setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public String getCreatedBy() {
        return this.createdBy;
    }

    @Override
    public TCapitalJobLog setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    @Override
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    @Override
    public TCapitalJobLog setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    @Override
    public TCapitalJobLog setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TCapitalJobLog (");

        sb.append(id);
        sb.append(", ").append(jobId);
        sb.append(", ").append(jobName);
        sb.append(", ").append(machineIp);
        sb.append(", ").append(status);
        sb.append(", ").append(errorMsg);
        sb.append(", ").append(startDate);
        sb.append(", ").append(endDate);
        sb.append(", ").append(shardingItem);
        sb.append(", ").append(execCount);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(updatedBy);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITCapitalJobLog from) {
        setId(from.getId());
        setJobId(from.getJobId());
        setJobName(from.getJobName());
        setMachineIp(from.getMachineIp());
        setStatus(from.getStatus());
        setErrorMsg(from.getErrorMsg());
        setStartDate(from.getStartDate());
        setEndDate(from.getEndDate());
        setShardingItem(from.getShardingItem());
        setExecCount(from.getExecCount());
        setCreatedAt(from.getCreatedAt());
        setCreatedBy(from.getCreatedBy());
        setUpdatedAt(from.getUpdatedAt());
        setUpdatedBy(from.getUpdatedBy());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITCapitalJobLog> E into(E into) {
        into.from(this);
        return into;
    }

    public TCapitalJobLog(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
