/*
 * This file is generated by jOOQ.
*/
package com.paulliu.jooq.tables.pojos;


import com.paulliu.jooq.tables.interfaces.ITCapitalJobConfig;

import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 定时任务配置表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TCapitalJobConfig implements ITCapitalJobConfig {

    private static final long serialVersionUID = -1512090359;

    private Long      id;
    private String    jobName;
    private String    jobEnv;
    private String    jobClass;
    private String    status;
    private String    isLoading;
    private Long      shardingTotalCount;
    private Long      execCount;
    private String    jobDesc;
    private Timestamp createdAt;
    private String    createdBy;
    private Timestamp updatedAt;
    private String    updatedBy;

    public TCapitalJobConfig() {}

    public TCapitalJobConfig(TCapitalJobConfig value) {
        this.id = value.id;
        this.jobName = value.jobName;
        this.jobEnv = value.jobEnv;
        this.jobClass = value.jobClass;
        this.status = value.status;
        this.isLoading = value.isLoading;
        this.shardingTotalCount = value.shardingTotalCount;
        this.execCount = value.execCount;
        this.jobDesc = value.jobDesc;
        this.createdAt = value.createdAt;
        this.createdBy = value.createdBy;
        this.updatedAt = value.updatedAt;
        this.updatedBy = value.updatedBy;
    }

    public TCapitalJobConfig(
        Long      id,
        String    jobName,
        String    jobEnv,
        String    jobClass,
        String    status,
        String    isLoading,
        Long      shardingTotalCount,
        Long      execCount,
        String    jobDesc,
        Timestamp createdAt,
        String    createdBy,
        Timestamp updatedAt,
        String    updatedBy
    ) {
        this.id = id;
        this.jobName = jobName;
        this.jobEnv = jobEnv;
        this.jobClass = jobClass;
        this.status = status;
        this.isLoading = isLoading;
        this.shardingTotalCount = shardingTotalCount;
        this.execCount = execCount;
        this.jobDesc = jobDesc;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
        this.updatedAt = updatedAt;
        this.updatedBy = updatedBy;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public TCapitalJobConfig setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public String getJobName() {
        return this.jobName;
    }

    @Override
    public TCapitalJobConfig setJobName(String jobName) {
        this.jobName = jobName;
        return this;
    }

    @Override
    public String getJobEnv() {
        return this.jobEnv;
    }

    @Override
    public TCapitalJobConfig setJobEnv(String jobEnv) {
        this.jobEnv = jobEnv;
        return this;
    }

    @Override
    public String getJobClass() {
        return this.jobClass;
    }

    @Override
    public TCapitalJobConfig setJobClass(String jobClass) {
        this.jobClass = jobClass;
        return this;
    }

    @Override
    public String getStatus() {
        return this.status;
    }

    @Override
    public TCapitalJobConfig setStatus(String status) {
        this.status = status;
        return this;
    }

    @Override
    public String getIsLoading() {
        return this.isLoading;
    }

    @Override
    public TCapitalJobConfig setIsLoading(String isLoading) {
        this.isLoading = isLoading;
        return this;
    }

    @Override
    public Long getShardingTotalCount() {
        return this.shardingTotalCount;
    }

    @Override
    public TCapitalJobConfig setShardingTotalCount(Long shardingTotalCount) {
        this.shardingTotalCount = shardingTotalCount;
        return this;
    }

    @Override
    public Long getExecCount() {
        return this.execCount;
    }

    @Override
    public TCapitalJobConfig setExecCount(Long execCount) {
        this.execCount = execCount;
        return this;
    }

    @Override
    public String getJobDesc() {
        return this.jobDesc;
    }

    @Override
    public TCapitalJobConfig setJobDesc(String jobDesc) {
        this.jobDesc = jobDesc;
        return this;
    }

    @Override
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public TCapitalJobConfig setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public String getCreatedBy() {
        return this.createdBy;
    }

    @Override
    public TCapitalJobConfig setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    @Override
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    @Override
    public TCapitalJobConfig setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    @Override
    public TCapitalJobConfig setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TCapitalJobConfig (");

        sb.append(id);
        sb.append(", ").append(jobName);
        sb.append(", ").append(jobEnv);
        sb.append(", ").append(jobClass);
        sb.append(", ").append(status);
        sb.append(", ").append(isLoading);
        sb.append(", ").append(shardingTotalCount);
        sb.append(", ").append(execCount);
        sb.append(", ").append(jobDesc);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(updatedBy);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITCapitalJobConfig from) {
        setId(from.getId());
        setJobName(from.getJobName());
        setJobEnv(from.getJobEnv());
        setJobClass(from.getJobClass());
        setStatus(from.getStatus());
        setIsLoading(from.getIsLoading());
        setShardingTotalCount(from.getShardingTotalCount());
        setExecCount(from.getExecCount());
        setJobDesc(from.getJobDesc());
        setCreatedAt(from.getCreatedAt());
        setCreatedBy(from.getCreatedBy());
        setUpdatedAt(from.getUpdatedAt());
        setUpdatedBy(from.getUpdatedBy());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITCapitalJobConfig> E into(E into) {
        into.from(this);
        return into;
    }

    public TCapitalJobConfig(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
