/*
 * This file is generated by jOOQ.
*/
package com.paulliu.jooq.tables.pojos;


import com.paulliu.jooq.tables.interfaces.ITCapitalControl;

import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 充转提控制表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TCapitalControl implements ITCapitalControl {

    private static final long serialVersionUID = -862103922;

    private Long      id;
    private String    controlType;
    private String    controlKey;
    private String    controlValue;
    private String    controlStatus;
    private Timestamp createdAt;
    private String    createdBy;
    private Timestamp updatedAt;
    private String    updatedBy;

    public TCapitalControl() {}

    public TCapitalControl(TCapitalControl value) {
        this.id = value.id;
        this.controlType = value.controlType;
        this.controlKey = value.controlKey;
        this.controlValue = value.controlValue;
        this.controlStatus = value.controlStatus;
        this.createdAt = value.createdAt;
        this.createdBy = value.createdBy;
        this.updatedAt = value.updatedAt;
        this.updatedBy = value.updatedBy;
    }

    public TCapitalControl(
        Long      id,
        String    controlType,
        String    controlKey,
        String    controlValue,
        String    controlStatus,
        Timestamp createdAt,
        String    createdBy,
        Timestamp updatedAt,
        String    updatedBy
    ) {
        this.id = id;
        this.controlType = controlType;
        this.controlKey = controlKey;
        this.controlValue = controlValue;
        this.controlStatus = controlStatus;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
        this.updatedAt = updatedAt;
        this.updatedBy = updatedBy;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public TCapitalControl setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public String getControlType() {
        return this.controlType;
    }

    @Override
    public TCapitalControl setControlType(String controlType) {
        this.controlType = controlType;
        return this;
    }

    @Override
    public String getControlKey() {
        return this.controlKey;
    }

    @Override
    public TCapitalControl setControlKey(String controlKey) {
        this.controlKey = controlKey;
        return this;
    }

    @Override
    public String getControlValue() {
        return this.controlValue;
    }

    @Override
    public TCapitalControl setControlValue(String controlValue) {
        this.controlValue = controlValue;
        return this;
    }

    @Override
    public String getControlStatus() {
        return this.controlStatus;
    }

    @Override
    public TCapitalControl setControlStatus(String controlStatus) {
        this.controlStatus = controlStatus;
        return this;
    }

    @Override
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public TCapitalControl setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public String getCreatedBy() {
        return this.createdBy;
    }

    @Override
    public TCapitalControl setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    @Override
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    @Override
    public TCapitalControl setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    @Override
    public TCapitalControl setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TCapitalControl (");

        sb.append(id);
        sb.append(", ").append(controlType);
        sb.append(", ").append(controlKey);
        sb.append(", ").append(controlValue);
        sb.append(", ").append(controlStatus);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(updatedBy);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITCapitalControl from) {
        setId(from.getId());
        setControlType(from.getControlType());
        setControlKey(from.getControlKey());
        setControlValue(from.getControlValue());
        setControlStatus(from.getControlStatus());
        setCreatedAt(from.getCreatedAt());
        setCreatedBy(from.getCreatedBy());
        setUpdatedAt(from.getUpdatedAt());
        setUpdatedBy(from.getUpdatedBy());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITCapitalControl> E into(E into) {
        into.from(this);
        return into;
    }

    public TCapitalControl(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
