/*
 * This file is generated by jOOQ.
*/
package com.paulliu.jooq.tables.pojos;


import com.paulliu.jooq.tables.interfaces.ITDemo;

import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TDemo implements ITDemo {

    private static final long serialVersionUID = -1419298835;

    private Integer    id;
    private String     name;
    private Byte       age;
    private BigDecimal money;
    private String     catalog;

    public TDemo() {}

    public TDemo(TDemo value) {
        this.id = value.id;
        this.name = value.name;
        this.age = value.age;
        this.money = value.money;
        this.catalog = value.catalog;
    }

    public TDemo(
        Integer    id,
        String     name,
        Byte       age,
        BigDecimal money,
        String     catalog
    ) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.money = money;
        this.catalog = catalog;
    }

    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public TDemo setId(Integer id) {
        this.id = id;
        return this;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public TDemo setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public Byte getAge() {
        return this.age;
    }

    @Override
    public TDemo setAge(Byte age) {
        this.age = age;
        return this;
    }

    @Override
    public BigDecimal getMoney() {
        return this.money;
    }

    @Override
    public TDemo setMoney(BigDecimal money) {
        this.money = money;
        return this;
    }

    @Override
    public String getCatalog() {
        return this.catalog;
    }

    @Override
    public TDemo setCatalog(String catalog) {
        this.catalog = catalog;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TDemo (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(age);
        sb.append(", ").append(money);
        sb.append(", ").append(catalog);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITDemo from) {
        setId(from.getId());
        setName(from.getName());
        setAge(from.getAge());
        setMoney(from.getMoney());
        setCatalog(from.getCatalog());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITDemo> E into(E into) {
        into.from(this);
        return into;
    }

    public TDemo(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
