/*
 * This file is generated by jOOQ.
*/
package com.paulliu.jooq.tables.pojos;


import com.paulliu.jooq.tables.interfaces.ITFianceTemp;

import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TFianceTemp implements ITFianceTemp {

    private static final long serialVersionUID = 468453631;

    private String    prodOfferName;
    private String    prodOfferId;
    private Timestamp finishTime;
    private String    accNbr;
    private String    custOrderId;
    private String    orderItemId;
    private Integer   rn;

    public TFianceTemp() {}

    public TFianceTemp(TFianceTemp value) {
        this.prodOfferName = value.prodOfferName;
        this.prodOfferId = value.prodOfferId;
        this.finishTime = value.finishTime;
        this.accNbr = value.accNbr;
        this.custOrderId = value.custOrderId;
        this.orderItemId = value.orderItemId;
        this.rn = value.rn;
    }

    public TFianceTemp(
        String    prodOfferName,
        String    prodOfferId,
        Timestamp finishTime,
        String    accNbr,
        String    custOrderId,
        String    orderItemId,
        Integer   rn
    ) {
        this.prodOfferName = prodOfferName;
        this.prodOfferId = prodOfferId;
        this.finishTime = finishTime;
        this.accNbr = accNbr;
        this.custOrderId = custOrderId;
        this.orderItemId = orderItemId;
        this.rn = rn;
    }

    @Override
    public String getProdOfferName() {
        return this.prodOfferName;
    }

    @Override
    public TFianceTemp setProdOfferName(String prodOfferName) {
        this.prodOfferName = prodOfferName;
        return this;
    }

    @Override
    public String getProdOfferId() {
        return this.prodOfferId;
    }

    @Override
    public TFianceTemp setProdOfferId(String prodOfferId) {
        this.prodOfferId = prodOfferId;
        return this;
    }

    @Override
    public Timestamp getFinishTime() {
        return this.finishTime;
    }

    @Override
    public TFianceTemp setFinishTime(Timestamp finishTime) {
        this.finishTime = finishTime;
        return this;
    }

    @Override
    public String getAccNbr() {
        return this.accNbr;
    }

    @Override
    public TFianceTemp setAccNbr(String accNbr) {
        this.accNbr = accNbr;
        return this;
    }

    @Override
    public String getCustOrderId() {
        return this.custOrderId;
    }

    @Override
    public TFianceTemp setCustOrderId(String custOrderId) {
        this.custOrderId = custOrderId;
        return this;
    }

    @Override
    public String getOrderItemId() {
        return this.orderItemId;
    }

    @Override
    public TFianceTemp setOrderItemId(String orderItemId) {
        this.orderItemId = orderItemId;
        return this;
    }

    @Override
    public Integer getRn() {
        return this.rn;
    }

    @Override
    public TFianceTemp setRn(Integer rn) {
        this.rn = rn;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TFianceTemp (");

        sb.append(prodOfferName);
        sb.append(", ").append(prodOfferId);
        sb.append(", ").append(finishTime);
        sb.append(", ").append(accNbr);
        sb.append(", ").append(custOrderId);
        sb.append(", ").append(orderItemId);
        sb.append(", ").append(rn);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITFianceTemp from) {
        setProdOfferName(from.getProdOfferName());
        setProdOfferId(from.getProdOfferId());
        setFinishTime(from.getFinishTime());
        setAccNbr(from.getAccNbr());
        setCustOrderId(from.getCustOrderId());
        setOrderItemId(from.getOrderItemId());
        setRn(from.getRn());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITFianceTemp> E into(E into) {
        into.from(this);
        return into;
    }

    public TFianceTemp(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
