/*
 * This file is generated by jOOQ.
*/
package com.paulliu.jooq.tables.pojos;


import com.paulliu.jooq.tables.interfaces.ITOther;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TOther implements ITOther {

    private static final long serialVersionUID = -1520068374;

    private Integer id;
    private String  otherName;
    private String  otherThing;

    public TOther() {}

    public TOther(TOther value) {
        this.id = value.id;
        this.otherName = value.otherName;
        this.otherThing = value.otherThing;
    }

    public TOther(
        Integer id,
        String  otherName,
        String  otherThing
    ) {
        this.id = id;
        this.otherName = otherName;
        this.otherThing = otherThing;
    }

    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public TOther setId(Integer id) {
        this.id = id;
        return this;
    }

    @Override
    public String getOtherName() {
        return this.otherName;
    }

    @Override
    public TOther setOtherName(String otherName) {
        this.otherName = otherName;
        return this;
    }

    @Override
    public String getOtherThing() {
        return this.otherThing;
    }

    @Override
    public TOther setOtherThing(String otherThing) {
        this.otherThing = otherThing;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TOther (");

        sb.append(id);
        sb.append(", ").append(otherName);
        sb.append(", ").append(otherThing);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITOther from) {
        setId(from.getId());
        setOtherName(from.getOtherName());
        setOtherThing(from.getOtherThing());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITOther> E into(E into) {
        into.from(this);
        return into;
    }

    public TOther(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
