/*
 * This file is generated by jOOQ.
*/
package com.paulliu.jooq.tables.pojos;


import com.paulliu.jooq.tables.interfaces.ITWithdrawOrder_201803;

import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 提现订单表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TWithdrawOrder_201803 implements ITWithdrawOrder_201803 {

    private static final long serialVersionUID = -783798238;

    private Long      id;
    private String    requestOrderNo;
    private String    withdrawOrderNo;
    private String    tradeNo;
    private String    tradeStatus;
    private Timestamp tradeFinishedDate;
    private Long      payAmt;
    private Long      discountAmt;
    private Long      feeAmt;
    private String    requestSystem;
    private Timestamp requestDate;
    private String    productCode;
    private String    tradeChannel;
    private String    customerNo;
    private String    customerType;
    private String    bankCardNo;
    private String    maskBankCardNo;
    private String    bankOrg;
    private String    bankName;
    private String    pubPriType;
    private String    customerName;
    private String    cardType;
    private Integer   amount;
    private String    ccy;
    private String    transReason;
    private String    operator;
    private String    memo;
    private String    resultCode;
    private String    resultMsg;
    private Timestamp createdAt;
    private String    createdBy;
    private Timestamp updatedAt;
    private String    updatedBy;

    public TWithdrawOrder_201803() {}

    public TWithdrawOrder_201803(TWithdrawOrder_201803 value) {
        this.id = value.id;
        this.requestOrderNo = value.requestOrderNo;
        this.withdrawOrderNo = value.withdrawOrderNo;
        this.tradeNo = value.tradeNo;
        this.tradeStatus = value.tradeStatus;
        this.tradeFinishedDate = value.tradeFinishedDate;
        this.payAmt = value.payAmt;
        this.discountAmt = value.discountAmt;
        this.feeAmt = value.feeAmt;
        this.requestSystem = value.requestSystem;
        this.requestDate = value.requestDate;
        this.productCode = value.productCode;
        this.tradeChannel = value.tradeChannel;
        this.customerNo = value.customerNo;
        this.customerType = value.customerType;
        this.bankCardNo = value.bankCardNo;
        this.maskBankCardNo = value.maskBankCardNo;
        this.bankOrg = value.bankOrg;
        this.bankName = value.bankName;
        this.pubPriType = value.pubPriType;
        this.customerName = value.customerName;
        this.cardType = value.cardType;
        this.amount = value.amount;
        this.ccy = value.ccy;
        this.transReason = value.transReason;
        this.operator = value.operator;
        this.memo = value.memo;
        this.resultCode = value.resultCode;
        this.resultMsg = value.resultMsg;
        this.createdAt = value.createdAt;
        this.createdBy = value.createdBy;
        this.updatedAt = value.updatedAt;
        this.updatedBy = value.updatedBy;
    }

    public TWithdrawOrder_201803(
        Long      id,
        String    requestOrderNo,
        String    withdrawOrderNo,
        String    tradeNo,
        String    tradeStatus,
        Timestamp tradeFinishedDate,
        Long      payAmt,
        Long      discountAmt,
        Long      feeAmt,
        String    requestSystem,
        Timestamp requestDate,
        String    productCode,
        String    tradeChannel,
        String    customerNo,
        String    customerType,
        String    bankCardNo,
        String    maskBankCardNo,
        String    bankOrg,
        String    bankName,
        String    pubPriType,
        String    customerName,
        String    cardType,
        Integer   amount,
        String    ccy,
        String    transReason,
        String    operator,
        String    memo,
        String    resultCode,
        String    resultMsg,
        Timestamp createdAt,
        String    createdBy,
        Timestamp updatedAt,
        String    updatedBy
    ) {
        this.id = id;
        this.requestOrderNo = requestOrderNo;
        this.withdrawOrderNo = withdrawOrderNo;
        this.tradeNo = tradeNo;
        this.tradeStatus = tradeStatus;
        this.tradeFinishedDate = tradeFinishedDate;
        this.payAmt = payAmt;
        this.discountAmt = discountAmt;
        this.feeAmt = feeAmt;
        this.requestSystem = requestSystem;
        this.requestDate = requestDate;
        this.productCode = productCode;
        this.tradeChannel = tradeChannel;
        this.customerNo = customerNo;
        this.customerType = customerType;
        this.bankCardNo = bankCardNo;
        this.maskBankCardNo = maskBankCardNo;
        this.bankOrg = bankOrg;
        this.bankName = bankName;
        this.pubPriType = pubPriType;
        this.customerName = customerName;
        this.cardType = cardType;
        this.amount = amount;
        this.ccy = ccy;
        this.transReason = transReason;
        this.operator = operator;
        this.memo = memo;
        this.resultCode = resultCode;
        this.resultMsg = resultMsg;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
        this.updatedAt = updatedAt;
        this.updatedBy = updatedBy;
    }

    @Override
    public Long getId() {
        return this.id;
    }

    @Override
    public TWithdrawOrder_201803 setId(Long id) {
        this.id = id;
        return this;
    }

    @Override
    public String getRequestOrderNo() {
        return this.requestOrderNo;
    }

    @Override
    public TWithdrawOrder_201803 setRequestOrderNo(String requestOrderNo) {
        this.requestOrderNo = requestOrderNo;
        return this;
    }

    @Override
    public String getWithdrawOrderNo() {
        return this.withdrawOrderNo;
    }

    @Override
    public TWithdrawOrder_201803 setWithdrawOrderNo(String withdrawOrderNo) {
        this.withdrawOrderNo = withdrawOrderNo;
        return this;
    }

    @Override
    public String getTradeNo() {
        return this.tradeNo;
    }

    @Override
    public TWithdrawOrder_201803 setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo;
        return this;
    }

    @Override
    public String getTradeStatus() {
        return this.tradeStatus;
    }

    @Override
    public TWithdrawOrder_201803 setTradeStatus(String tradeStatus) {
        this.tradeStatus = tradeStatus;
        return this;
    }

    @Override
    public Timestamp getTradeFinishedDate() {
        return this.tradeFinishedDate;
    }

    @Override
    public TWithdrawOrder_201803 setTradeFinishedDate(Timestamp tradeFinishedDate) {
        this.tradeFinishedDate = tradeFinishedDate;
        return this;
    }

    @Override
    public Long getPayAmt() {
        return this.payAmt;
    }

    @Override
    public TWithdrawOrder_201803 setPayAmt(Long payAmt) {
        this.payAmt = payAmt;
        return this;
    }

    @Override
    public Long getDiscountAmt() {
        return this.discountAmt;
    }

    @Override
    public TWithdrawOrder_201803 setDiscountAmt(Long discountAmt) {
        this.discountAmt = discountAmt;
        return this;
    }

    @Override
    public Long getFeeAmt() {
        return this.feeAmt;
    }

    @Override
    public TWithdrawOrder_201803 setFeeAmt(Long feeAmt) {
        this.feeAmt = feeAmt;
        return this;
    }

    @Override
    public String getRequestSystem() {
        return this.requestSystem;
    }

    @Override
    public TWithdrawOrder_201803 setRequestSystem(String requestSystem) {
        this.requestSystem = requestSystem;
        return this;
    }

    @Override
    public Timestamp getRequestDate() {
        return this.requestDate;
    }

    @Override
    public TWithdrawOrder_201803 setRequestDate(Timestamp requestDate) {
        this.requestDate = requestDate;
        return this;
    }

    @Override
    public String getProductCode() {
        return this.productCode;
    }

    @Override
    public TWithdrawOrder_201803 setProductCode(String productCode) {
        this.productCode = productCode;
        return this;
    }

    @Override
    public String getTradeChannel() {
        return this.tradeChannel;
    }

    @Override
    public TWithdrawOrder_201803 setTradeChannel(String tradeChannel) {
        this.tradeChannel = tradeChannel;
        return this;
    }

    @Override
    public String getCustomerNo() {
        return this.customerNo;
    }

    @Override
    public TWithdrawOrder_201803 setCustomerNo(String customerNo) {
        this.customerNo = customerNo;
        return this;
    }

    @Override
    public String getCustomerType() {
        return this.customerType;
    }

    @Override
    public TWithdrawOrder_201803 setCustomerType(String customerType) {
        this.customerType = customerType;
        return this;
    }

    @Override
    public String getBankCardNo() {
        return this.bankCardNo;
    }

    @Override
    public TWithdrawOrder_201803 setBankCardNo(String bankCardNo) {
        this.bankCardNo = bankCardNo;
        return this;
    }

    @Override
    public String getMaskBankCardNo() {
        return this.maskBankCardNo;
    }

    @Override
    public TWithdrawOrder_201803 setMaskBankCardNo(String maskBankCardNo) {
        this.maskBankCardNo = maskBankCardNo;
        return this;
    }

    @Override
    public String getBankOrg() {
        return this.bankOrg;
    }

    @Override
    public TWithdrawOrder_201803 setBankOrg(String bankOrg) {
        this.bankOrg = bankOrg;
        return this;
    }

    @Override
    public String getBankName() {
        return this.bankName;
    }

    @Override
    public TWithdrawOrder_201803 setBankName(String bankName) {
        this.bankName = bankName;
        return this;
    }

    @Override
    public String getPubPriType() {
        return this.pubPriType;
    }

    @Override
    public TWithdrawOrder_201803 setPubPriType(String pubPriType) {
        this.pubPriType = pubPriType;
        return this;
    }

    @Override
    public String getCustomerName() {
        return this.customerName;
    }

    @Override
    public TWithdrawOrder_201803 setCustomerName(String customerName) {
        this.customerName = customerName;
        return this;
    }

    @Override
    public String getCardType() {
        return this.cardType;
    }

    @Override
    public TWithdrawOrder_201803 setCardType(String cardType) {
        this.cardType = cardType;
        return this;
    }

    @Override
    public Integer getAmount() {
        return this.amount;
    }

    @Override
    public TWithdrawOrder_201803 setAmount(Integer amount) {
        this.amount = amount;
        return this;
    }

    @Override
    public String getCcy() {
        return this.ccy;
    }

    @Override
    public TWithdrawOrder_201803 setCcy(String ccy) {
        this.ccy = ccy;
        return this;
    }

    @Override
    public String getTransReason() {
        return this.transReason;
    }

    @Override
    public TWithdrawOrder_201803 setTransReason(String transReason) {
        this.transReason = transReason;
        return this;
    }

    @Override
    public String getOperator() {
        return this.operator;
    }

    @Override
    public TWithdrawOrder_201803 setOperator(String operator) {
        this.operator = operator;
        return this;
    }

    @Override
    public String getMemo() {
        return this.memo;
    }

    @Override
    public TWithdrawOrder_201803 setMemo(String memo) {
        this.memo = memo;
        return this;
    }

    @Override
    public String getResultCode() {
        return this.resultCode;
    }

    @Override
    public TWithdrawOrder_201803 setResultCode(String resultCode) {
        this.resultCode = resultCode;
        return this;
    }

    @Override
    public String getResultMsg() {
        return this.resultMsg;
    }

    @Override
    public TWithdrawOrder_201803 setResultMsg(String resultMsg) {
        this.resultMsg = resultMsg;
        return this;
    }

    @Override
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    @Override
    public TWithdrawOrder_201803 setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public String getCreatedBy() {
        return this.createdBy;
    }

    @Override
    public TWithdrawOrder_201803 setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    @Override
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    @Override
    public TWithdrawOrder_201803 setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    @Override
    public TWithdrawOrder_201803 setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TWithdrawOrder_201803 (");

        sb.append(id);
        sb.append(", ").append(requestOrderNo);
        sb.append(", ").append(withdrawOrderNo);
        sb.append(", ").append(tradeNo);
        sb.append(", ").append(tradeStatus);
        sb.append(", ").append(tradeFinishedDate);
        sb.append(", ").append(payAmt);
        sb.append(", ").append(discountAmt);
        sb.append(", ").append(feeAmt);
        sb.append(", ").append(requestSystem);
        sb.append(", ").append(requestDate);
        sb.append(", ").append(productCode);
        sb.append(", ").append(tradeChannel);
        sb.append(", ").append(customerNo);
        sb.append(", ").append(customerType);
        sb.append(", ").append(bankCardNo);
        sb.append(", ").append(maskBankCardNo);
        sb.append(", ").append(bankOrg);
        sb.append(", ").append(bankName);
        sb.append(", ").append(pubPriType);
        sb.append(", ").append(customerName);
        sb.append(", ").append(cardType);
        sb.append(", ").append(amount);
        sb.append(", ").append(ccy);
        sb.append(", ").append(transReason);
        sb.append(", ").append(operator);
        sb.append(", ").append(memo);
        sb.append(", ").append(resultCode);
        sb.append(", ").append(resultMsg);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(updatedBy);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITWithdrawOrder_201803 from) {
        setId(from.getId());
        setRequestOrderNo(from.getRequestOrderNo());
        setWithdrawOrderNo(from.getWithdrawOrderNo());
        setTradeNo(from.getTradeNo());
        setTradeStatus(from.getTradeStatus());
        setTradeFinishedDate(from.getTradeFinishedDate());
        setPayAmt(from.getPayAmt());
        setDiscountAmt(from.getDiscountAmt());
        setFeeAmt(from.getFeeAmt());
        setRequestSystem(from.getRequestSystem());
        setRequestDate(from.getRequestDate());
        setProductCode(from.getProductCode());
        setTradeChannel(from.getTradeChannel());
        setCustomerNo(from.getCustomerNo());
        setCustomerType(from.getCustomerType());
        setBankCardNo(from.getBankCardNo());
        setMaskBankCardNo(from.getMaskBankCardNo());
        setBankOrg(from.getBankOrg());
        setBankName(from.getBankName());
        setPubPriType(from.getPubPriType());
        setCustomerName(from.getCustomerName());
        setCardType(from.getCardType());
        setAmount(from.getAmount());
        setCcy(from.getCcy());
        setTransReason(from.getTransReason());
        setOperator(from.getOperator());
        setMemo(from.getMemo());
        setResultCode(from.getResultCode());
        setResultMsg(from.getResultMsg());
        setCreatedAt(from.getCreatedAt());
        setCreatedBy(from.getCreatedBy());
        setUpdatedAt(from.getUpdatedAt());
        setUpdatedBy(from.getUpdatedBy());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITWithdrawOrder_201803> E into(E into) {
        into.from(this);
        return into;
    }

    public TWithdrawOrder_201803(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
