/*
 * This file is generated by jOOQ.
*/
package com.paulliu.jooq.tables.records;


import com.paulliu.jooq.tables.TBonuspackageInfo;
import com.paulliu.jooq.tables.interfaces.ITBonuspackageInfo;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 红包套餐属性表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TBonuspackageInfoRecord extends UpdatableRecordImpl<TBonuspackageInfoRecord> implements Record14<Long, String, String, String, String, Date, Date, String, Date, String, Timestamp, String, Timestamp, String>, ITBonuspackageInfo {

    private static final long serialVersionUID = -1132982547;

    /**
     * Setter for <code>test.T_BONUSPACKAGE_INFO.ID</code>. 主键
     */
    @Override
    public TBonuspackageInfoRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>test.T_BONUSPACKAGE_INFO.ID</code>. 主键
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>test.T_BONUSPACKAGE_INFO.PRODUCT_NO</code>. 用户手机号
     */
    @Override
    public TBonuspackageInfoRecord setProductNo(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>test.T_BONUSPACKAGE_INFO.PRODUCT_NO</code>. 用户手机号
     */
    @Override
    public String getProductNo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test.T_BONUSPACKAGE_INFO.CONTRACT_NO</code>. 客户账户号
     */
    @Override
    public TBonuspackageInfoRecord setContractNo(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>test.T_BONUSPACKAGE_INFO.CONTRACT_NO</code>. 客户账户号
     */
    @Override
    public String getContractNo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>test.T_BONUSPACKAGE_INFO.PROMPT_CODE</code>. 销售产品号
     */
    @Override
    public TBonuspackageInfoRecord setPromptCode(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>test.T_BONUSPACKAGE_INFO.PROMPT_CODE</code>. 销售产品号
     */
    @Override
    public String getPromptCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>test.T_BONUSPACKAGE_INFO.PROTOCOL_VERSION</code>. 协议版本
     */
    @Override
    public TBonuspackageInfoRecord setProtocolVersion(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>test.T_BONUSPACKAGE_INFO.PROTOCOL_VERSION</code>. 协议版本
     */
    @Override
    public String getProtocolVersion() {
        return (String) get(4);
    }

    /**
     * Setter for <code>test.T_BONUSPACKAGE_INFO.PROTOCOL_BEGIN_AT</code>. 协议生效日期
     */
    @Override
    public TBonuspackageInfoRecord setProtocolBeginAt(Date value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>test.T_BONUSPACKAGE_INFO.PROTOCOL_BEGIN_AT</code>. 协议生效日期
     */
    @Override
    public Date getProtocolBeginAt() {
        return (Date) get(5);
    }

    /**
     * Setter for <code>test.T_BONUSPACKAGE_INFO.PROTOCOL_END_AT</code>. 协议失效日期
     */
    @Override
    public TBonuspackageInfoRecord setProtocolEndAt(Date value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>test.T_BONUSPACKAGE_INFO.PROTOCOL_END_AT</code>. 协议失效日期
     */
    @Override
    public Date getProtocolEndAt() {
        return (Date) get(6);
    }

    /**
     * Setter for <code>test.T_BONUSPACKAGE_INFO.REBATE_CYCLE</code>. 返利期数
     */
    @Override
    public TBonuspackageInfoRecord setRebateCycle(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>test.T_BONUSPACKAGE_INFO.REBATE_CYCLE</code>. 返利期数
     */
    @Override
    public String getRebateCycle() {
        return (String) get(7);
    }

    /**
     * Setter for <code>test.T_BONUSPACKAGE_INFO.FIRST_REBATE_AT</code>. 首次返利时间
     */
    @Override
    public TBonuspackageInfoRecord setFirstRebateAt(Date value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>test.T_BONUSPACKAGE_INFO.FIRST_REBATE_AT</code>. 首次返利时间
     */
    @Override
    public Date getFirstRebateAt() {
        return (Date) get(8);
    }

    /**
     * Setter for <code>test.T_BONUSPACKAGE_INFO.PROTOCOL_STATUS</code>. 状态：ENABLE-可用，DISABLE-不可用，DISCRAD-废弃
     */
    @Override
    public TBonuspackageInfoRecord setProtocolStatus(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>test.T_BONUSPACKAGE_INFO.PROTOCOL_STATUS</code>. 状态：ENABLE-可用，DISABLE-不可用，DISCRAD-废弃
     */
    @Override
    public String getProtocolStatus() {
        return (String) get(9);
    }

    /**
     * Setter for <code>test.T_BONUSPACKAGE_INFO.CREATED_AT</code>. 创建时间
     */
    @Override
    public TBonuspackageInfoRecord setCreatedAt(Timestamp value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>test.T_BONUSPACKAGE_INFO.CREATED_AT</code>. 创建时间
     */
    @Override
    public Timestamp getCreatedAt() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>test.T_BONUSPACKAGE_INFO.CREATED_BY</code>. 创建用户
     */
    @Override
    public TBonuspackageInfoRecord setCreatedBy(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>test.T_BONUSPACKAGE_INFO.CREATED_BY</code>. 创建用户
     */
    @Override
    public String getCreatedBy() {
        return (String) get(11);
    }

    /**
     * Setter for <code>test.T_BONUSPACKAGE_INFO.UPDATED_AT</code>. 更新时间
     */
    @Override
    public TBonuspackageInfoRecord setUpdatedAt(Timestamp value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>test.T_BONUSPACKAGE_INFO.UPDATED_AT</code>. 更新时间
     */
    @Override
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(12);
    }

    /**
     * Setter for <code>test.T_BONUSPACKAGE_INFO.UPDATED_BY</code>. 更新用户
     */
    @Override
    public TBonuspackageInfoRecord setUpdatedBy(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>test.T_BONUSPACKAGE_INFO.UPDATED_BY</code>. 更新用户
     */
    @Override
    public String getUpdatedBy() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Long, String, String, String, String, Date, Date, String, Date, String, Timestamp, String, Timestamp, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Long, String, String, String, String, Date, Date, String, Date, String, Timestamp, String, Timestamp, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TBonuspackageInfo.T_BONUSPACKAGE_INFO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TBonuspackageInfo.T_BONUSPACKAGE_INFO.PRODUCT_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TBonuspackageInfo.T_BONUSPACKAGE_INFO.CONTRACT_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TBonuspackageInfo.T_BONUSPACKAGE_INFO.PROMPT_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TBonuspackageInfo.T_BONUSPACKAGE_INFO.PROTOCOL_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field6() {
        return TBonuspackageInfo.T_BONUSPACKAGE_INFO.PROTOCOL_BEGIN_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field7() {
        return TBonuspackageInfo.T_BONUSPACKAGE_INFO.PROTOCOL_END_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TBonuspackageInfo.T_BONUSPACKAGE_INFO.REBATE_CYCLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field9() {
        return TBonuspackageInfo.T_BONUSPACKAGE_INFO.FIRST_REBATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return TBonuspackageInfo.T_BONUSPACKAGE_INFO.PROTOCOL_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return TBonuspackageInfo.T_BONUSPACKAGE_INFO.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return TBonuspackageInfo.T_BONUSPACKAGE_INFO.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field13() {
        return TBonuspackageInfo.T_BONUSPACKAGE_INFO.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return TBonuspackageInfo.T_BONUSPACKAGE_INFO.UPDATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getProductNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getContractNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPromptCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getProtocolVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component6() {
        return getProtocolBeginAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component7() {
        return getProtocolEndAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getRebateCycle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component9() {
        return getFirstRebateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getProtocolStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component13() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getProductNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getContractNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPromptCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getProtocolVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value6() {
        return getProtocolBeginAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value7() {
        return getProtocolEndAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getRebateCycle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value9() {
        return getFirstRebateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getProtocolStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value13() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBonuspackageInfoRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBonuspackageInfoRecord value2(String value) {
        setProductNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBonuspackageInfoRecord value3(String value) {
        setContractNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBonuspackageInfoRecord value4(String value) {
        setPromptCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBonuspackageInfoRecord value5(String value) {
        setProtocolVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBonuspackageInfoRecord value6(Date value) {
        setProtocolBeginAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBonuspackageInfoRecord value7(Date value) {
        setProtocolEndAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBonuspackageInfoRecord value8(String value) {
        setRebateCycle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBonuspackageInfoRecord value9(Date value) {
        setFirstRebateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBonuspackageInfoRecord value10(String value) {
        setProtocolStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBonuspackageInfoRecord value11(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBonuspackageInfoRecord value12(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBonuspackageInfoRecord value13(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBonuspackageInfoRecord value14(String value) {
        setUpdatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TBonuspackageInfoRecord values(Long value1, String value2, String value3, String value4, String value5, Date value6, Date value7, String value8, Date value9, String value10, Timestamp value11, String value12, Timestamp value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITBonuspackageInfo from) {
        setId(from.getId());
        setProductNo(from.getProductNo());
        setContractNo(from.getContractNo());
        setPromptCode(from.getPromptCode());
        setProtocolVersion(from.getProtocolVersion());
        setProtocolBeginAt(from.getProtocolBeginAt());
        setProtocolEndAt(from.getProtocolEndAt());
        setRebateCycle(from.getRebateCycle());
        setFirstRebateAt(from.getFirstRebateAt());
        setProtocolStatus(from.getProtocolStatus());
        setCreatedAt(from.getCreatedAt());
        setCreatedBy(from.getCreatedBy());
        setUpdatedAt(from.getUpdatedAt());
        setUpdatedBy(from.getUpdatedBy());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITBonuspackageInfo> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TBonuspackageInfoRecord
     */
    public TBonuspackageInfoRecord() {
        super(TBonuspackageInfo.T_BONUSPACKAGE_INFO);
    }

    /**
     * Create a detached, initialised TBonuspackageInfoRecord
     */
    public TBonuspackageInfoRecord(Long id, String productNo, String contractNo, String promptCode, String protocolVersion, Date protocolBeginAt, Date protocolEndAt, String rebateCycle, Date firstRebateAt, String protocolStatus, Timestamp createdAt, String createdBy, Timestamp updatedAt, String updatedBy) {
        super(TBonuspackageInfo.T_BONUSPACKAGE_INFO);

        set(0, id);
        set(1, productNo);
        set(2, contractNo);
        set(3, promptCode);
        set(4, protocolVersion);
        set(5, protocolBeginAt);
        set(6, protocolEndAt);
        set(7, rebateCycle);
        set(8, firstRebateAt);
        set(9, protocolStatus);
        set(10, createdAt);
        set(11, createdBy);
        set(12, updatedAt);
        set(13, updatedBy);
    }

    public TBonuspackageInfoRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
