/*
 * This file is generated by jOOQ.
*/
package com.paulliu.jooq.tables.records;


import com.paulliu.jooq.tables.TCapitalJobLog;
import com.paulliu.jooq.tables.interfaces.ITCapitalJobLog;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 定时任务日志表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TCapitalJobLogRecord extends UpdatableRecordImpl<TCapitalJobLogRecord> implements Record14<Long, Long, String, String, String, String, Timestamp, Timestamp, Long, Long, Timestamp, String, Timestamp, String>, ITCapitalJobLog {

    private static final long serialVersionUID = 2021739256;

    /**
     * Setter for <code>test.t_capital_job_log.id</code>. id
     */
    @Override
    public TCapitalJobLogRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_job_log.id</code>. id
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>test.t_capital_job_log.job_id</code>. 任务id
     */
    @Override
    public TCapitalJobLogRecord setJobId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_job_log.job_id</code>. 任务id
     */
    @Override
    public Long getJobId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>test.t_capital_job_log.job_name</code>. 任务名称
     */
    @Override
    public TCapitalJobLogRecord setJobName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_job_log.job_name</code>. 任务名称
     */
    @Override
    public String getJobName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>test.t_capital_job_log.machine_ip</code>. 机器ip地址
     */
    @Override
    public TCapitalJobLogRecord setMachineIp(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_job_log.machine_ip</code>. 机器ip地址
     */
    @Override
    public String getMachineIp() {
        return (String) get(3);
    }

    /**
     * Setter for <code>test.t_capital_job_log.status</code>. 任务执行状态:success:成功、fail:失败
     */
    @Override
    public TCapitalJobLogRecord setStatus(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_job_log.status</code>. 任务执行状态:success:成功、fail:失败
     */
    @Override
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>test.t_capital_job_log.error_msg</code>. 任务异常信息
     */
    @Override
    public TCapitalJobLogRecord setErrorMsg(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_job_log.error_msg</code>. 任务异常信息
     */
    @Override
    public String getErrorMsg() {
        return (String) get(5);
    }

    /**
     * Setter for <code>test.t_capital_job_log.start_date</code>. 任务开始时间
     */
    @Override
    public TCapitalJobLogRecord setStartDate(Timestamp value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_job_log.start_date</code>. 任务开始时间
     */
    @Override
    public Timestamp getStartDate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>test.t_capital_job_log.end_date</code>. 任务结束时间
     */
    @Override
    public TCapitalJobLogRecord setEndDate(Timestamp value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_job_log.end_date</code>. 任务结束时间
     */
    @Override
    public Timestamp getEndDate() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>test.t_capital_job_log.sharding_item</code>. 分片序号
     */
    @Override
    public TCapitalJobLogRecord setShardingItem(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_job_log.sharding_item</code>. 分片序号
     */
    @Override
    public Long getShardingItem() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>test.t_capital_job_log.exec_count</code>. 单任务处理条数
     */
    @Override
    public TCapitalJobLogRecord setExecCount(Long value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_job_log.exec_count</code>. 单任务处理条数
     */
    @Override
    public Long getExecCount() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>test.t_capital_job_log.created_at</code>. 创建时间
     */
    @Override
    public TCapitalJobLogRecord setCreatedAt(Timestamp value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_job_log.created_at</code>. 创建时间
     */
    @Override
    public Timestamp getCreatedAt() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>test.t_capital_job_log.created_by</code>. 创建人
     */
    @Override
    public TCapitalJobLogRecord setCreatedBy(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_job_log.created_by</code>. 创建人
     */
    @Override
    public String getCreatedBy() {
        return (String) get(11);
    }

    /**
     * Setter for <code>test.t_capital_job_log.updated_at</code>. 修改时间
     */
    @Override
    public TCapitalJobLogRecord setUpdatedAt(Timestamp value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_job_log.updated_at</code>. 修改时间
     */
    @Override
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(12);
    }

    /**
     * Setter for <code>test.t_capital_job_log.updated_by</code>. 修改人
     */
    @Override
    public TCapitalJobLogRecord setUpdatedBy(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_job_log.updated_by</code>. 修改人
     */
    @Override
    public String getUpdatedBy() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Long, Long, String, String, String, String, Timestamp, Timestamp, Long, Long, Timestamp, String, Timestamp, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Long, Long, String, String, String, String, Timestamp, Timestamp, Long, Long, Timestamp, String, Timestamp, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TCapitalJobLog.T_CAPITAL_JOB_LOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return TCapitalJobLog.T_CAPITAL_JOB_LOG.JOB_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TCapitalJobLog.T_CAPITAL_JOB_LOG.JOB_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TCapitalJobLog.T_CAPITAL_JOB_LOG.MACHINE_IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TCapitalJobLog.T_CAPITAL_JOB_LOG.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TCapitalJobLog.T_CAPITAL_JOB_LOG.ERROR_MSG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return TCapitalJobLog.T_CAPITAL_JOB_LOG.START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return TCapitalJobLog.T_CAPITAL_JOB_LOG.END_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return TCapitalJobLog.T_CAPITAL_JOB_LOG.SHARDING_ITEM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return TCapitalJobLog.T_CAPITAL_JOB_LOG.EXEC_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return TCapitalJobLog.T_CAPITAL_JOB_LOG.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return TCapitalJobLog.T_CAPITAL_JOB_LOG.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field13() {
        return TCapitalJobLog.T_CAPITAL_JOB_LOG.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return TCapitalJobLog.T_CAPITAL_JOB_LOG.UPDATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getJobId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getJobName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getMachineIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getErrorMsg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component9() {
        return getShardingItem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component10() {
        return getExecCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component13() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getJobId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getJobName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMachineIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getErrorMsg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getShardingItem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getExecCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value13() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalJobLogRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalJobLogRecord value2(Long value) {
        setJobId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalJobLogRecord value3(String value) {
        setJobName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalJobLogRecord value4(String value) {
        setMachineIp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalJobLogRecord value5(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalJobLogRecord value6(String value) {
        setErrorMsg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalJobLogRecord value7(Timestamp value) {
        setStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalJobLogRecord value8(Timestamp value) {
        setEndDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalJobLogRecord value9(Long value) {
        setShardingItem(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalJobLogRecord value10(Long value) {
        setExecCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalJobLogRecord value11(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalJobLogRecord value12(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalJobLogRecord value13(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalJobLogRecord value14(String value) {
        setUpdatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalJobLogRecord values(Long value1, Long value2, String value3, String value4, String value5, String value6, Timestamp value7, Timestamp value8, Long value9, Long value10, Timestamp value11, String value12, Timestamp value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITCapitalJobLog from) {
        setId(from.getId());
        setJobId(from.getJobId());
        setJobName(from.getJobName());
        setMachineIp(from.getMachineIp());
        setStatus(from.getStatus());
        setErrorMsg(from.getErrorMsg());
        setStartDate(from.getStartDate());
        setEndDate(from.getEndDate());
        setShardingItem(from.getShardingItem());
        setExecCount(from.getExecCount());
        setCreatedAt(from.getCreatedAt());
        setCreatedBy(from.getCreatedBy());
        setUpdatedAt(from.getUpdatedAt());
        setUpdatedBy(from.getUpdatedBy());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITCapitalJobLog> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TCapitalJobLogRecord
     */
    public TCapitalJobLogRecord() {
        super(TCapitalJobLog.T_CAPITAL_JOB_LOG);
    }

    /**
     * Create a detached, initialised TCapitalJobLogRecord
     */
    public TCapitalJobLogRecord(Long id, Long jobId, String jobName, String machineIp, String status, String errorMsg, Timestamp startDate, Timestamp endDate, Long shardingItem, Long execCount, Timestamp createdAt, String createdBy, Timestamp updatedAt, String updatedBy) {
        super(TCapitalJobLog.T_CAPITAL_JOB_LOG);

        set(0, id);
        set(1, jobId);
        set(2, jobName);
        set(3, machineIp);
        set(4, status);
        set(5, errorMsg);
        set(6, startDate);
        set(7, endDate);
        set(8, shardingItem);
        set(9, execCount);
        set(10, createdAt);
        set(11, createdBy);
        set(12, updatedAt);
        set(13, updatedBy);
    }

    public TCapitalJobLogRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
