/*
 * This file is generated by jOOQ.
*/
package com.paulliu.jooq.tables.records;


import com.paulliu.jooq.tables.TCapitalControl;
import com.paulliu.jooq.tables.interfaces.ITCapitalControl;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 充转提控制表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TCapitalControlRecord extends UpdatableRecordImpl<TCapitalControlRecord> implements Record9<Long, String, String, String, String, Timestamp, String, Timestamp, String>, ITCapitalControl {

    private static final long serialVersionUID = 1180071875;

    /**
     * Setter for <code>test.t_capital_control.id</code>. ID
     */
    @Override
    public TCapitalControlRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_control.id</code>. ID
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>test.t_capital_control.control_type</code>. 控制类型
     */
    @Override
    public TCapitalControlRecord setControlType(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_control.control_type</code>. 控制类型
     */
    @Override
    public String getControlType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test.t_capital_control.control_key</code>. KEY
     */
    @Override
    public TCapitalControlRecord setControlKey(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_control.control_key</code>. KEY
     */
    @Override
    public String getControlKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>test.t_capital_control.control_value</code>. VALUE
     */
    @Override
    public TCapitalControlRecord setControlValue(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_control.control_value</code>. VALUE
     */
    @Override
    public String getControlValue() {
        return (String) get(3);
    }

    /**
     * Setter for <code>test.t_capital_control.control_status</code>. 状态
     */
    @Override
    public TCapitalControlRecord setControlStatus(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_control.control_status</code>. 状态
     */
    @Override
    public String getControlStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>test.t_capital_control.created_at</code>. 创建时间
     */
    @Override
    public TCapitalControlRecord setCreatedAt(Timestamp value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_control.created_at</code>. 创建时间
     */
    @Override
    public Timestamp getCreatedAt() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>test.t_capital_control.created_by</code>. 创建人
     */
    @Override
    public TCapitalControlRecord setCreatedBy(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_control.created_by</code>. 创建人
     */
    @Override
    public String getCreatedBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>test.t_capital_control.updated_at</code>. 修改时间
     */
    @Override
    public TCapitalControlRecord setUpdatedAt(Timestamp value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_control.updated_at</code>. 修改时间
     */
    @Override
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>test.t_capital_control.updated_by</code>. 修改人
     */
    @Override
    public TCapitalControlRecord setUpdatedBy(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_control.updated_by</code>. 修改人
     */
    @Override
    public String getUpdatedBy() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, String, String, String, Timestamp, String, Timestamp, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, String, String, String, Timestamp, String, Timestamp, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TCapitalControl.T_CAPITAL_CONTROL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TCapitalControl.T_CAPITAL_CONTROL.CONTROL_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TCapitalControl.T_CAPITAL_CONTROL.CONTROL_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TCapitalControl.T_CAPITAL_CONTROL.CONTROL_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TCapitalControl.T_CAPITAL_CONTROL.CONTROL_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return TCapitalControl.T_CAPITAL_CONTROL.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TCapitalControl.T_CAPITAL_CONTROL.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return TCapitalControl.T_CAPITAL_CONTROL.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return TCapitalControl.T_CAPITAL_CONTROL.UPDATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getControlType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getControlKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getControlValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getControlStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getControlType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getControlKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getControlValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getControlStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalControlRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalControlRecord value2(String value) {
        setControlType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalControlRecord value3(String value) {
        setControlKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalControlRecord value4(String value) {
        setControlValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalControlRecord value5(String value) {
        setControlStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalControlRecord value6(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalControlRecord value7(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalControlRecord value8(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalControlRecord value9(String value) {
        setUpdatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalControlRecord values(Long value1, String value2, String value3, String value4, String value5, Timestamp value6, String value7, Timestamp value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITCapitalControl from) {
        setId(from.getId());
        setControlType(from.getControlType());
        setControlKey(from.getControlKey());
        setControlValue(from.getControlValue());
        setControlStatus(from.getControlStatus());
        setCreatedAt(from.getCreatedAt());
        setCreatedBy(from.getCreatedBy());
        setUpdatedAt(from.getUpdatedAt());
        setUpdatedBy(from.getUpdatedBy());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITCapitalControl> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TCapitalControlRecord
     */
    public TCapitalControlRecord() {
        super(TCapitalControl.T_CAPITAL_CONTROL);
    }

    /**
     * Create a detached, initialised TCapitalControlRecord
     */
    public TCapitalControlRecord(Long id, String controlType, String controlKey, String controlValue, String controlStatus, Timestamp createdAt, String createdBy, Timestamp updatedAt, String updatedBy) {
        super(TCapitalControl.T_CAPITAL_CONTROL);

        set(0, id);
        set(1, controlType);
        set(2, controlKey);
        set(3, controlValue);
        set(4, controlStatus);
        set(5, createdAt);
        set(6, createdBy);
        set(7, updatedAt);
        set(8, updatedBy);
    }

    public TCapitalControlRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
