/*
 * This file is generated by jOOQ.
*/
package com.paulliu.jooq.tables.records;


import com.paulliu.jooq.tables.TCapitalJobConfig;
import com.paulliu.jooq.tables.interfaces.ITCapitalJobConfig;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 定时任务配置表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TCapitalJobConfigRecord extends UpdatableRecordImpl<TCapitalJobConfigRecord> implements Record13<Long, String, String, String, String, String, Long, Long, String, Timestamp, String, Timestamp, String>, ITCapitalJobConfig {

    private static final long serialVersionUID = 24462098;

    /**
     * Setter for <code>test.t_capital_job_config.id</code>. ID
     */
    @Override
    public TCapitalJobConfigRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_job_config.id</code>. ID
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>test.t_capital_job_config.job_name</code>. 任务名称（类名或者bean名）
     */
    @Override
    public TCapitalJobConfigRecord setJobName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_job_config.job_name</code>. 任务名称（类名或者bean名）
     */
    @Override
    public String getJobName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test.t_capital_job_config.job_env</code>. 任务运行环境:DEV:开发环境、TEST:综测环境、PRE_PRODUCE:准生产环境、PRODUCE:生产环境
     */
    @Override
    public TCapitalJobConfigRecord setJobEnv(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_job_config.job_env</code>. 任务运行环境:DEV:开发环境、TEST:综测环境、PRE_PRODUCE:准生产环境、PRODUCE:生产环境
     */
    @Override
    public String getJobEnv() {
        return (String) get(2);
    }

    /**
     * Setter for <code>test.t_capital_job_config.job_class</code>. 类名全路径
     */
    @Override
    public TCapitalJobConfigRecord setJobClass(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_job_config.job_class</code>. 类名全路径
     */
    @Override
    public String getJobClass() {
        return (String) get(3);
    }

    /**
     * Setter for <code>test.t_capital_job_config.status</code>. 状态:normal:有效
     */
    @Override
    public TCapitalJobConfigRecord setStatus(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_job_config.status</code>. 状态:normal:有效
     */
    @Override
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>test.t_capital_job_config.is_loading</code>. 运行状态：loading:待运行,running:正在运行
     */
    @Override
    public TCapitalJobConfigRecord setIsLoading(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_job_config.is_loading</code>. 运行状态：loading:待运行,running:正在运行
     */
    @Override
    public String getIsLoading() {
        return (String) get(5);
    }

    /**
     * Setter for <code>test.t_capital_job_config.sharding_total_count</code>. 分片总数
     */
    @Override
    public TCapitalJobConfigRecord setShardingTotalCount(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_job_config.sharding_total_count</code>. 分片总数
     */
    @Override
    public Long getShardingTotalCount() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>test.t_capital_job_config.exec_count</code>. 单任务处理条数
     */
    @Override
    public TCapitalJobConfigRecord setExecCount(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_job_config.exec_count</code>. 单任务处理条数
     */
    @Override
    public Long getExecCount() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>test.t_capital_job_config.job_desc</code>. 任务描述
     */
    @Override
    public TCapitalJobConfigRecord setJobDesc(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_job_config.job_desc</code>. 任务描述
     */
    @Override
    public String getJobDesc() {
        return (String) get(8);
    }

    /**
     * Setter for <code>test.t_capital_job_config.created_at</code>. 创建时间
     */
    @Override
    public TCapitalJobConfigRecord setCreatedAt(Timestamp value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_job_config.created_at</code>. 创建时间
     */
    @Override
    public Timestamp getCreatedAt() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>test.t_capital_job_config.created_by</code>. 创建人
     */
    @Override
    public TCapitalJobConfigRecord setCreatedBy(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_job_config.created_by</code>. 创建人
     */
    @Override
    public String getCreatedBy() {
        return (String) get(10);
    }

    /**
     * Setter for <code>test.t_capital_job_config.updated_at</code>. 修改时间
     */
    @Override
    public TCapitalJobConfigRecord setUpdatedAt(Timestamp value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_job_config.updated_at</code>. 修改时间
     */
    @Override
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>test.t_capital_job_config.updated_by</code>. 修改人
     */
    @Override
    public TCapitalJobConfigRecord setUpdatedBy(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>test.t_capital_job_config.updated_by</code>. 修改人
     */
    @Override
    public String getUpdatedBy() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Long, String, String, String, String, String, Long, Long, String, Timestamp, String, Timestamp, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Long, String, String, String, String, String, Long, Long, String, Timestamp, String, Timestamp, String> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.JOB_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.JOB_ENV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.JOB_CLASS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.IS_LOADING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.SHARDING_TOTAL_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.EXEC_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.JOB_DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.UPDATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getJobName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getJobEnv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getJobClass();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getIsLoading();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getShardingTotalCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getExecCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getJobDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component12() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getJobName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getJobEnv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getJobClass();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getIsLoading();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getShardingTotalCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getExecCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getJobDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalJobConfigRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalJobConfigRecord value2(String value) {
        setJobName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalJobConfigRecord value3(String value) {
        setJobEnv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalJobConfigRecord value4(String value) {
        setJobClass(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalJobConfigRecord value5(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalJobConfigRecord value6(String value) {
        setIsLoading(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalJobConfigRecord value7(Long value) {
        setShardingTotalCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalJobConfigRecord value8(Long value) {
        setExecCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalJobConfigRecord value9(String value) {
        setJobDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalJobConfigRecord value10(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalJobConfigRecord value11(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalJobConfigRecord value12(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalJobConfigRecord value13(String value) {
        setUpdatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TCapitalJobConfigRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, Long value7, Long value8, String value9, Timestamp value10, String value11, Timestamp value12, String value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITCapitalJobConfig from) {
        setId(from.getId());
        setJobName(from.getJobName());
        setJobEnv(from.getJobEnv());
        setJobClass(from.getJobClass());
        setStatus(from.getStatus());
        setIsLoading(from.getIsLoading());
        setShardingTotalCount(from.getShardingTotalCount());
        setExecCount(from.getExecCount());
        setJobDesc(from.getJobDesc());
        setCreatedAt(from.getCreatedAt());
        setCreatedBy(from.getCreatedBy());
        setUpdatedAt(from.getUpdatedAt());
        setUpdatedBy(from.getUpdatedBy());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITCapitalJobConfig> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TCapitalJobConfigRecord
     */
    public TCapitalJobConfigRecord() {
        super(TCapitalJobConfig.T_CAPITAL_JOB_CONFIG);
    }

    /**
     * Create a detached, initialised TCapitalJobConfigRecord
     */
    public TCapitalJobConfigRecord(Long id, String jobName, String jobEnv, String jobClass, String status, String isLoading, Long shardingTotalCount, Long execCount, String jobDesc, Timestamp createdAt, String createdBy, Timestamp updatedAt, String updatedBy) {
        super(TCapitalJobConfig.T_CAPITAL_JOB_CONFIG);

        set(0, id);
        set(1, jobName);
        set(2, jobEnv);
        set(3, jobClass);
        set(4, status);
        set(5, isLoading);
        set(6, shardingTotalCount);
        set(7, execCount);
        set(8, jobDesc);
        set(9, createdAt);
        set(10, createdBy);
        set(11, updatedAt);
        set(12, updatedBy);
    }

    public TCapitalJobConfigRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
