/*
 * This file is generated by jOOQ.
*/
package com.paulliu.jooq.tables.records;


import com.paulliu.jooq.tables.TWithdrawOrder_201803;
import com.paulliu.jooq.tables.interfaces.ITWithdrawOrder_201803;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 提现订单表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TWithdrawOrder_201803Record extends UpdatableRecordImpl<TWithdrawOrder_201803Record> implements ITWithdrawOrder_201803 {

    private static final long serialVersionUID = 700042306;

    /**
     * Setter for <code>test.t_withdraw_order_201803.id</code>. 主键
     */
    @Override
    public TWithdrawOrder_201803Record setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.id</code>. 主键
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.request_order_no</code>. 请求系统单号
     */
    @Override
    public TWithdrawOrder_201803Record setRequestOrderNo(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.request_order_no</code>. 请求系统单号
     */
    @Override
    public String getRequestOrderNo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.withdraw_order_no</code>. 提现单号
     */
    @Override
    public TWithdrawOrder_201803Record setWithdrawOrderNo(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.withdraw_order_no</code>. 提现单号
     */
    @Override
    public String getWithdrawOrderNo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.trade_no</code>. 交易号
     */
    @Override
    public TWithdrawOrder_201803Record setTradeNo(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.trade_no</code>. 交易号
     */
    @Override
    public String getTradeNo() {
        return (String) get(3);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.trade_status</code>. 交易状态
     */
    @Override
    public TWithdrawOrder_201803Record setTradeStatus(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.trade_status</code>. 交易状态
     */
    @Override
    public String getTradeStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.trade_finished_date</code>. 交易完成时间
     */
    @Override
    public TWithdrawOrder_201803Record setTradeFinishedDate(Timestamp value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.trade_finished_date</code>. 交易完成时间
     */
    @Override
    public Timestamp getTradeFinishedDate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.pay_amt</code>. 实际支付金额
     */
    @Override
    public TWithdrawOrder_201803Record setPayAmt(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.pay_amt</code>. 实际支付金额
     */
    @Override
    public Long getPayAmt() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.discount_amt</code>. 优惠金额
     */
    @Override
    public TWithdrawOrder_201803Record setDiscountAmt(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.discount_amt</code>. 优惠金额
     */
    @Override
    public Long getDiscountAmt() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.fee_amt</code>. 手续费金额
     */
    @Override
    public TWithdrawOrder_201803Record setFeeAmt(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.fee_amt</code>. 手续费金额
     */
    @Override
    public Long getFeeAmt() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.request_system</code>. 请求系统
     */
    @Override
    public TWithdrawOrder_201803Record setRequestSystem(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.request_system</code>. 请求系统
     */
    @Override
    public String getRequestSystem() {
        return (String) get(9);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.request_date</code>. 请求时间
     */
    @Override
    public TWithdrawOrder_201803Record setRequestDate(Timestamp value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.request_date</code>. 请求时间
     */
    @Override
    public Timestamp getRequestDate() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.product_code</code>. 产品码
     */
    @Override
    public TWithdrawOrder_201803Record setProductCode(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.product_code</code>. 产品码
     */
    @Override
    public String getProductCode() {
        return (String) get(11);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.trade_channel</code>. 交易渠道
     */
    @Override
    public TWithdrawOrder_201803Record setTradeChannel(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.trade_channel</code>. 交易渠道
     */
    @Override
    public String getTradeChannel() {
        return (String) get(12);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.customer_no</code>. 账号
     */
    @Override
    public TWithdrawOrder_201803Record setCustomerNo(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.customer_no</code>. 账号
     */
    @Override
    public String getCustomerNo() {
        return (String) get(13);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.customer_type</code>. 客户类型 OPERATOR_NO-操作员号  MERCHANT_NO-商户号
     */
    @Override
    public TWithdrawOrder_201803Record setCustomerType(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.customer_type</code>. 客户类型 OPERATOR_NO-操作员号  MERCHANT_NO-商户号
     */
    @Override
    public String getCustomerType() {
        return (String) get(14);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.bank_card_no</code>. 银行卡号
     */
    @Override
    public TWithdrawOrder_201803Record setBankCardNo(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.bank_card_no</code>. 银行卡号
     */
    @Override
    public String getBankCardNo() {
        return (String) get(15);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.mask_bank_card_no</code>. 银行卡号掩码
     */
    @Override
    public TWithdrawOrder_201803Record setMaskBankCardNo(String value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.mask_bank_card_no</code>. 银行卡号掩码
     */
    @Override
    public String getMaskBankCardNo() {
        return (String) get(16);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.bank_org</code>. 银行机构-英文简称
     */
    @Override
    public TWithdrawOrder_201803Record setBankOrg(String value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.bank_org</code>. 银行机构-英文简称
     */
    @Override
    public String getBankOrg() {
        return (String) get(17);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.bank_name</code>. 银行名称-中文名称
     */
    @Override
    public TWithdrawOrder_201803Record setBankName(String value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.bank_name</code>. 银行名称-中文名称
     */
    @Override
    public String getBankName() {
        return (String) get(18);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.pub_pri_type</code>. 公私标识--PUBLIC:对公业务；PRIVATE：对私业务
     */
    @Override
    public TWithdrawOrder_201803Record setPubPriType(String value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.pub_pri_type</code>. 公私标识--PUBLIC:对公业务；PRIVATE：对私业务
     */
    @Override
    public String getPubPriType() {
        return (String) get(19);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.customer_name</code>. 客户姓名
     */
    @Override
    public TWithdrawOrder_201803Record setCustomerName(String value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.customer_name</code>. 客户姓名
     */
    @Override
    public String getCustomerName() {
        return (String) get(20);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.card_type</code>. 卡类型--DEBIT：借记卡;CREDIT：贷记卡
     */
    @Override
    public TWithdrawOrder_201803Record setCardType(String value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.card_type</code>. 卡类型--DEBIT：借记卡;CREDIT：贷记卡
     */
    @Override
    public String getCardType() {
        return (String) get(21);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.amount</code>. 金额
     */
    @Override
    public TWithdrawOrder_201803Record setAmount(Integer value) {
        set(22, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.amount</code>. 金额
     */
    @Override
    public Integer getAmount() {
        return (Integer) get(22);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.ccy</code>. 币种
     */
    @Override
    public TWithdrawOrder_201803Record setCcy(String value) {
        set(23, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.ccy</code>. 币种
     */
    @Override
    public String getCcy() {
        return (String) get(23);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.trans_reason</code>. 交易原因
     */
    @Override
    public TWithdrawOrder_201803Record setTransReason(String value) {
        set(24, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.trans_reason</code>. 交易原因
     */
    @Override
    public String getTransReason() {
        return (String) get(24);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.operator</code>. 操作人
     */
    @Override
    public TWithdrawOrder_201803Record setOperator(String value) {
        set(25, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.operator</code>. 操作人
     */
    @Override
    public String getOperator() {
        return (String) get(25);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.memo</code>. 备注
     */
    @Override
    public TWithdrawOrder_201803Record setMemo(String value) {
        set(26, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.memo</code>. 备注
     */
    @Override
    public String getMemo() {
        return (String) get(26);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.result_code</code>. 结果码
     */
    @Override
    public TWithdrawOrder_201803Record setResultCode(String value) {
        set(27, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.result_code</code>. 结果码
     */
    @Override
    public String getResultCode() {
        return (String) get(27);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.result_msg</code>. 结果消息
     */
    @Override
    public TWithdrawOrder_201803Record setResultMsg(String value) {
        set(28, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.result_msg</code>. 结果消息
     */
    @Override
    public String getResultMsg() {
        return (String) get(28);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.created_at</code>. 创建时间
     */
    @Override
    public TWithdrawOrder_201803Record setCreatedAt(Timestamp value) {
        set(29, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.created_at</code>. 创建时间
     */
    @Override
    public Timestamp getCreatedAt() {
        return (Timestamp) get(29);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.created_by</code>. 创建人
     */
    @Override
    public TWithdrawOrder_201803Record setCreatedBy(String value) {
        set(30, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.created_by</code>. 创建人
     */
    @Override
    public String getCreatedBy() {
        return (String) get(30);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.updated_at</code>. 修改时间
     */
    @Override
    public TWithdrawOrder_201803Record setUpdatedAt(Timestamp value) {
        set(31, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.updated_at</code>. 修改时间
     */
    @Override
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(31);
    }

    /**
     * Setter for <code>test.t_withdraw_order_201803.updated_by</code>. 修改人
     */
    @Override
    public TWithdrawOrder_201803Record setUpdatedBy(String value) {
        set(32, value);
        return this;
    }

    /**
     * Getter for <code>test.t_withdraw_order_201803.updated_by</code>. 修改人
     */
    @Override
    public String getUpdatedBy() {
        return (String) get(32);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ITWithdrawOrder_201803 from) {
        setId(from.getId());
        setRequestOrderNo(from.getRequestOrderNo());
        setWithdrawOrderNo(from.getWithdrawOrderNo());
        setTradeNo(from.getTradeNo());
        setTradeStatus(from.getTradeStatus());
        setTradeFinishedDate(from.getTradeFinishedDate());
        setPayAmt(from.getPayAmt());
        setDiscountAmt(from.getDiscountAmt());
        setFeeAmt(from.getFeeAmt());
        setRequestSystem(from.getRequestSystem());
        setRequestDate(from.getRequestDate());
        setProductCode(from.getProductCode());
        setTradeChannel(from.getTradeChannel());
        setCustomerNo(from.getCustomerNo());
        setCustomerType(from.getCustomerType());
        setBankCardNo(from.getBankCardNo());
        setMaskBankCardNo(from.getMaskBankCardNo());
        setBankOrg(from.getBankOrg());
        setBankName(from.getBankName());
        setPubPriType(from.getPubPriType());
        setCustomerName(from.getCustomerName());
        setCardType(from.getCardType());
        setAmount(from.getAmount());
        setCcy(from.getCcy());
        setTransReason(from.getTransReason());
        setOperator(from.getOperator());
        setMemo(from.getMemo());
        setResultCode(from.getResultCode());
        setResultMsg(from.getResultMsg());
        setCreatedAt(from.getCreatedAt());
        setCreatedBy(from.getCreatedBy());
        setUpdatedAt(from.getUpdatedAt());
        setUpdatedBy(from.getUpdatedBy());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ITWithdrawOrder_201803> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TWithdrawOrder_201803Record
     */
    public TWithdrawOrder_201803Record() {
        super(TWithdrawOrder_201803.T_WITHDRAW_ORDER_201803);
    }

    /**
     * Create a detached, initialised TWithdrawOrder_201803Record
     */
    public TWithdrawOrder_201803Record(Long id, String requestOrderNo, String withdrawOrderNo, String tradeNo, String tradeStatus, Timestamp tradeFinishedDate, Long payAmt, Long discountAmt, Long feeAmt, String requestSystem, Timestamp requestDate, String productCode, String tradeChannel, String customerNo, String customerType, String bankCardNo, String maskBankCardNo, String bankOrg, String bankName, String pubPriType, String customerName, String cardType, Integer amount, String ccy, String transReason, String operator, String memo, String resultCode, String resultMsg, Timestamp createdAt, String createdBy, Timestamp updatedAt, String updatedBy) {
        super(TWithdrawOrder_201803.T_WITHDRAW_ORDER_201803);

        set(0, id);
        set(1, requestOrderNo);
        set(2, withdrawOrderNo);
        set(3, tradeNo);
        set(4, tradeStatus);
        set(5, tradeFinishedDate);
        set(6, payAmt);
        set(7, discountAmt);
        set(8, feeAmt);
        set(9, requestSystem);
        set(10, requestDate);
        set(11, productCode);
        set(12, tradeChannel);
        set(13, customerNo);
        set(14, customerType);
        set(15, bankCardNo);
        set(16, maskBankCardNo);
        set(17, bankOrg);
        set(18, bankName);
        set(19, pubPriType);
        set(20, customerName);
        set(21, cardType);
        set(22, amount);
        set(23, ccy);
        set(24, transReason);
        set(25, operator);
        set(26, memo);
        set(27, resultCode);
        set(28, resultMsg);
        set(29, createdAt);
        set(30, createdBy);
        set(31, updatedAt);
        set(32, updatedBy);
    }

    public TWithdrawOrder_201803Record(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
