/*
 * This file is generated by jOOQ.
*/
package com.paulliu.jooq;


import com.paulliu.jooq.tables.TBonuspackageInfo;
import com.paulliu.jooq.tables.TCapitalControl;
import com.paulliu.jooq.tables.TCapitalJobConfig;
import com.paulliu.jooq.tables.TCapitalJobLog;
import com.paulliu.jooq.tables.TDemo;
import com.paulliu.jooq.tables.TOther;
import com.paulliu.jooq.tables.TWithdrawOrder_201803;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>test</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index T_BONUSPACKAGE_INFO_PRIMARY = Indexes0.T_BONUSPACKAGE_INFO_PRIMARY;
    public static final Index T_CAPITAL_CONTROL_I_CAPITAL_CONTROL_TYPE_KEY = Indexes0.T_CAPITAL_CONTROL_I_CAPITAL_CONTROL_TYPE_KEY;
    public static final Index T_CAPITAL_CONTROL_PRIMARY = Indexes0.T_CAPITAL_CONTROL_PRIMARY;
    public static final Index T_CAPITAL_JOB_CONFIG_IU_JOB_CONFIG_JOB_NAME = Indexes0.T_CAPITAL_JOB_CONFIG_IU_JOB_CONFIG_JOB_NAME;
    public static final Index T_CAPITAL_JOB_CONFIG_PRIMARY = Indexes0.T_CAPITAL_JOB_CONFIG_PRIMARY;
    public static final Index T_CAPITAL_JOB_LOG_IDX_CAPITAL_JOB_LOG_JOB_ID_PK = Indexes0.T_CAPITAL_JOB_LOG_IDX_CAPITAL_JOB_LOG_JOB_ID_PK;
    public static final Index T_CAPITAL_JOB_LOG_PRIMARY = Indexes0.T_CAPITAL_JOB_LOG_PRIMARY;
    public static final Index T_DEMO_PRIMARY = Indexes0.T_DEMO_PRIMARY;
    public static final Index T_OTHER_PRIMARY = Indexes0.T_OTHER_PRIMARY;
    public static final Index T_WITHDRAW_ORDER_201803_IDX_MNO_RNO_RSY_PK = Indexes0.T_WITHDRAW_ORDER_201803_IDX_MNO_RNO_RSY_PK;
    public static final Index T_WITHDRAW_ORDER_201803_IDX_TRADE_NO_PK = Indexes0.T_WITHDRAW_ORDER_201803_IDX_TRADE_NO_PK;
    public static final Index T_WITHDRAW_ORDER_201803_IDX_WITHDRAW_ORDER_NO_PK = Indexes0.T_WITHDRAW_ORDER_201803_IDX_WITHDRAW_ORDER_NO_PK;
    public static final Index T_WITHDRAW_ORDER_201803_PRIMARY = Indexes0.T_WITHDRAW_ORDER_201803_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index T_BONUSPACKAGE_INFO_PRIMARY = Internal.createIndex("PRIMARY", TBonuspackageInfo.T_BONUSPACKAGE_INFO, new OrderField[] { TBonuspackageInfo.T_BONUSPACKAGE_INFO.ID }, true);
        public static Index T_CAPITAL_CONTROL_I_CAPITAL_CONTROL_TYPE_KEY = Internal.createIndex("I_CAPITAL_CONTROL_TYPE_KEY", TCapitalControl.T_CAPITAL_CONTROL, new OrderField[] { TCapitalControl.T_CAPITAL_CONTROL.CONTROL_TYPE, TCapitalControl.T_CAPITAL_CONTROL.CONTROL_KEY }, true);
        public static Index T_CAPITAL_CONTROL_PRIMARY = Internal.createIndex("PRIMARY", TCapitalControl.T_CAPITAL_CONTROL, new OrderField[] { TCapitalControl.T_CAPITAL_CONTROL.ID }, true);
        public static Index T_CAPITAL_JOB_CONFIG_IU_JOB_CONFIG_JOB_NAME = Internal.createIndex("IU_JOB_CONFIG_JOB_NAME", TCapitalJobConfig.T_CAPITAL_JOB_CONFIG, new OrderField[] { TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.JOB_NAME, TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.JOB_ENV }, true);
        public static Index T_CAPITAL_JOB_CONFIG_PRIMARY = Internal.createIndex("PRIMARY", TCapitalJobConfig.T_CAPITAL_JOB_CONFIG, new OrderField[] { TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.ID }, true);
        public static Index T_CAPITAL_JOB_LOG_IDX_CAPITAL_JOB_LOG_JOB_ID_PK = Internal.createIndex("idx_capital_job_log_job_id_pk", TCapitalJobLog.T_CAPITAL_JOB_LOG, new OrderField[] { TCapitalJobLog.T_CAPITAL_JOB_LOG.JOB_ID }, false);
        public static Index T_CAPITAL_JOB_LOG_PRIMARY = Internal.createIndex("PRIMARY", TCapitalJobLog.T_CAPITAL_JOB_LOG, new OrderField[] { TCapitalJobLog.T_CAPITAL_JOB_LOG.ID }, true);
        public static Index T_DEMO_PRIMARY = Internal.createIndex("PRIMARY", TDemo.T_DEMO, new OrderField[] { TDemo.T_DEMO.ID }, true);
        public static Index T_OTHER_PRIMARY = Internal.createIndex("PRIMARY", TOther.T_OTHER, new OrderField[] { TOther.T_OTHER.ID }, true);
        public static Index T_WITHDRAW_ORDER_201803_IDX_MNO_RNO_RSY_PK = Internal.createIndex("idx_mno_rno_rsy_pk", TWithdrawOrder_201803.T_WITHDRAW_ORDER_201803, new OrderField[] { TWithdrawOrder_201803.T_WITHDRAW_ORDER_201803.CUSTOMER_NO, TWithdrawOrder_201803.T_WITHDRAW_ORDER_201803.REQUEST_ORDER_NO, TWithdrawOrder_201803.T_WITHDRAW_ORDER_201803.REQUEST_SYSTEM }, false);
        public static Index T_WITHDRAW_ORDER_201803_IDX_TRADE_NO_PK = Internal.createIndex("idx_trade_no_pk", TWithdrawOrder_201803.T_WITHDRAW_ORDER_201803, new OrderField[] { TWithdrawOrder_201803.T_WITHDRAW_ORDER_201803.TRADE_NO }, false);
        public static Index T_WITHDRAW_ORDER_201803_IDX_WITHDRAW_ORDER_NO_PK = Internal.createIndex("idx_withdraw_order_no_pk", TWithdrawOrder_201803.T_WITHDRAW_ORDER_201803, new OrderField[] { TWithdrawOrder_201803.T_WITHDRAW_ORDER_201803.WITHDRAW_ORDER_NO }, false);
        public static Index T_WITHDRAW_ORDER_201803_PRIMARY = Internal.createIndex("PRIMARY", TWithdrawOrder_201803.T_WITHDRAW_ORDER_201803, new OrderField[] { TWithdrawOrder_201803.T_WITHDRAW_ORDER_201803.ID }, true);
    }
}
