/*
 * This file is generated by jOOQ.
*/
package com.paulliu.jooq;


import com.paulliu.jooq.tables.TBonuspackageInfo;
import com.paulliu.jooq.tables.TCapitalControl;
import com.paulliu.jooq.tables.TCapitalJobConfig;
import com.paulliu.jooq.tables.TCapitalJobLog;
import com.paulliu.jooq.tables.TDemo;
import com.paulliu.jooq.tables.TOther;
import com.paulliu.jooq.tables.TWithdrawOrder_201803;
import com.paulliu.jooq.tables.records.TBonuspackageInfoRecord;
import com.paulliu.jooq.tables.records.TCapitalControlRecord;
import com.paulliu.jooq.tables.records.TCapitalJobConfigRecord;
import com.paulliu.jooq.tables.records.TCapitalJobLogRecord;
import com.paulliu.jooq.tables.records.TDemoRecord;
import com.paulliu.jooq.tables.records.TOtherRecord;
import com.paulliu.jooq.tables.records.TWithdrawOrder_201803Record;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>test</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<TBonuspackageInfoRecord, Long> IDENTITY_T_BONUSPACKAGE_INFO = Identities0.IDENTITY_T_BONUSPACKAGE_INFO;
    public static final Identity<TCapitalControlRecord, Long> IDENTITY_T_CAPITAL_CONTROL = Identities0.IDENTITY_T_CAPITAL_CONTROL;
    public static final Identity<TCapitalJobConfigRecord, Long> IDENTITY_T_CAPITAL_JOB_CONFIG = Identities0.IDENTITY_T_CAPITAL_JOB_CONFIG;
    public static final Identity<TCapitalJobLogRecord, Long> IDENTITY_T_CAPITAL_JOB_LOG = Identities0.IDENTITY_T_CAPITAL_JOB_LOG;
    public static final Identity<TDemoRecord, Integer> IDENTITY_T_DEMO = Identities0.IDENTITY_T_DEMO;
    public static final Identity<TOtherRecord, Integer> IDENTITY_T_OTHER = Identities0.IDENTITY_T_OTHER;
    public static final Identity<TWithdrawOrder_201803Record, Long> IDENTITY_T_WITHDRAW_ORDER_201803 = Identities0.IDENTITY_T_WITHDRAW_ORDER_201803;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TBonuspackageInfoRecord> KEY_T_BONUSPACKAGE_INFO_PRIMARY = UniqueKeys0.KEY_T_BONUSPACKAGE_INFO_PRIMARY;
    public static final UniqueKey<TCapitalControlRecord> KEY_T_CAPITAL_CONTROL_PRIMARY = UniqueKeys0.KEY_T_CAPITAL_CONTROL_PRIMARY;
    public static final UniqueKey<TCapitalControlRecord> KEY_T_CAPITAL_CONTROL_I_CAPITAL_CONTROL_TYPE_KEY = UniqueKeys0.KEY_T_CAPITAL_CONTROL_I_CAPITAL_CONTROL_TYPE_KEY;
    public static final UniqueKey<TCapitalJobConfigRecord> KEY_T_CAPITAL_JOB_CONFIG_PRIMARY = UniqueKeys0.KEY_T_CAPITAL_JOB_CONFIG_PRIMARY;
    public static final UniqueKey<TCapitalJobConfigRecord> KEY_T_CAPITAL_JOB_CONFIG_IU_JOB_CONFIG_JOB_NAME = UniqueKeys0.KEY_T_CAPITAL_JOB_CONFIG_IU_JOB_CONFIG_JOB_NAME;
    public static final UniqueKey<TCapitalJobLogRecord> KEY_T_CAPITAL_JOB_LOG_PRIMARY = UniqueKeys0.KEY_T_CAPITAL_JOB_LOG_PRIMARY;
    public static final UniqueKey<TDemoRecord> KEY_T_DEMO_PRIMARY = UniqueKeys0.KEY_T_DEMO_PRIMARY;
    public static final UniqueKey<TOtherRecord> KEY_T_OTHER_PRIMARY = UniqueKeys0.KEY_T_OTHER_PRIMARY;
    public static final UniqueKey<TWithdrawOrder_201803Record> KEY_T_WITHDRAW_ORDER_201803_PRIMARY = UniqueKeys0.KEY_T_WITHDRAW_ORDER_201803_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<TBonuspackageInfoRecord, Long> IDENTITY_T_BONUSPACKAGE_INFO = Internal.createIdentity(TBonuspackageInfo.T_BONUSPACKAGE_INFO, TBonuspackageInfo.T_BONUSPACKAGE_INFO.ID);
        public static Identity<TCapitalControlRecord, Long> IDENTITY_T_CAPITAL_CONTROL = Internal.createIdentity(TCapitalControl.T_CAPITAL_CONTROL, TCapitalControl.T_CAPITAL_CONTROL.ID);
        public static Identity<TCapitalJobConfigRecord, Long> IDENTITY_T_CAPITAL_JOB_CONFIG = Internal.createIdentity(TCapitalJobConfig.T_CAPITAL_JOB_CONFIG, TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.ID);
        public static Identity<TCapitalJobLogRecord, Long> IDENTITY_T_CAPITAL_JOB_LOG = Internal.createIdentity(TCapitalJobLog.T_CAPITAL_JOB_LOG, TCapitalJobLog.T_CAPITAL_JOB_LOG.ID);
        public static Identity<TDemoRecord, Integer> IDENTITY_T_DEMO = Internal.createIdentity(TDemo.T_DEMO, TDemo.T_DEMO.ID);
        public static Identity<TOtherRecord, Integer> IDENTITY_T_OTHER = Internal.createIdentity(TOther.T_OTHER, TOther.T_OTHER.ID);
        public static Identity<TWithdrawOrder_201803Record, Long> IDENTITY_T_WITHDRAW_ORDER_201803 = Internal.createIdentity(TWithdrawOrder_201803.T_WITHDRAW_ORDER_201803, TWithdrawOrder_201803.T_WITHDRAW_ORDER_201803.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<TBonuspackageInfoRecord> KEY_T_BONUSPACKAGE_INFO_PRIMARY = Internal.createUniqueKey(TBonuspackageInfo.T_BONUSPACKAGE_INFO, "KEY_T_BONUSPACKAGE_INFO_PRIMARY", TBonuspackageInfo.T_BONUSPACKAGE_INFO.ID);
        public static final UniqueKey<TCapitalControlRecord> KEY_T_CAPITAL_CONTROL_PRIMARY = Internal.createUniqueKey(TCapitalControl.T_CAPITAL_CONTROL, "KEY_t_capital_control_PRIMARY", TCapitalControl.T_CAPITAL_CONTROL.ID);
        public static final UniqueKey<TCapitalControlRecord> KEY_T_CAPITAL_CONTROL_I_CAPITAL_CONTROL_TYPE_KEY = Internal.createUniqueKey(TCapitalControl.T_CAPITAL_CONTROL, "KEY_t_capital_control_I_CAPITAL_CONTROL_TYPE_KEY", TCapitalControl.T_CAPITAL_CONTROL.CONTROL_TYPE, TCapitalControl.T_CAPITAL_CONTROL.CONTROL_KEY);
        public static final UniqueKey<TCapitalJobConfigRecord> KEY_T_CAPITAL_JOB_CONFIG_PRIMARY = Internal.createUniqueKey(TCapitalJobConfig.T_CAPITAL_JOB_CONFIG, "KEY_t_capital_job_config_PRIMARY", TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.ID);
        public static final UniqueKey<TCapitalJobConfigRecord> KEY_T_CAPITAL_JOB_CONFIG_IU_JOB_CONFIG_JOB_NAME = Internal.createUniqueKey(TCapitalJobConfig.T_CAPITAL_JOB_CONFIG, "KEY_t_capital_job_config_IU_JOB_CONFIG_JOB_NAME", TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.JOB_NAME, TCapitalJobConfig.T_CAPITAL_JOB_CONFIG.JOB_ENV);
        public static final UniqueKey<TCapitalJobLogRecord> KEY_T_CAPITAL_JOB_LOG_PRIMARY = Internal.createUniqueKey(TCapitalJobLog.T_CAPITAL_JOB_LOG, "KEY_t_capital_job_log_PRIMARY", TCapitalJobLog.T_CAPITAL_JOB_LOG.ID);
        public static final UniqueKey<TDemoRecord> KEY_T_DEMO_PRIMARY = Internal.createUniqueKey(TDemo.T_DEMO, "KEY_t_demo_PRIMARY", TDemo.T_DEMO.ID);
        public static final UniqueKey<TOtherRecord> KEY_T_OTHER_PRIMARY = Internal.createUniqueKey(TOther.T_OTHER, "KEY_t_other_PRIMARY", TOther.T_OTHER.ID);
        public static final UniqueKey<TWithdrawOrder_201803Record> KEY_T_WITHDRAW_ORDER_201803_PRIMARY = Internal.createUniqueKey(TWithdrawOrder_201803.T_WITHDRAW_ORDER_201803, "KEY_t_withdraw_order_201803_PRIMARY", TWithdrawOrder_201803.T_WITHDRAW_ORDER_201803.ID);
    }
}
