/*
 * This file is generated by jOOQ.
*/
package com.paulliu.jooq;


import com.paulliu.jooq.tables.TBonuspackageInfo;
import com.paulliu.jooq.tables.TCapitalControl;
import com.paulliu.jooq.tables.TCapitalJobConfig;
import com.paulliu.jooq.tables.TCapitalJobLog;
import com.paulliu.jooq.tables.TDemo;
import com.paulliu.jooq.tables.TFianceTemp;
import com.paulliu.jooq.tables.TOther;
import com.paulliu.jooq.tables.TWithdrawOrder_201803;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test extends SchemaImpl {

    private static final long serialVersionUID = 346042162;

    /**
     * The reference instance of <code>test</code>
     */
    public static final Test TEST = new Test();

    /**
     * 红包套餐属性表
     */
    public final TBonuspackageInfo T_BONUSPACKAGE_INFO = com.paulliu.jooq.tables.TBonuspackageInfo.T_BONUSPACKAGE_INFO;

    /**
     * 充转提控制表
     */
    public final TCapitalControl T_CAPITAL_CONTROL = com.paulliu.jooq.tables.TCapitalControl.T_CAPITAL_CONTROL;

    /**
     * 定时任务配置表
     */
    public final TCapitalJobConfig T_CAPITAL_JOB_CONFIG = com.paulliu.jooq.tables.TCapitalJobConfig.T_CAPITAL_JOB_CONFIG;

    /**
     * 定时任务日志表
     */
    public final TCapitalJobLog T_CAPITAL_JOB_LOG = com.paulliu.jooq.tables.TCapitalJobLog.T_CAPITAL_JOB_LOG;

    /**
     * The table <code>test.t_demo</code>.
     */
    public final TDemo T_DEMO = com.paulliu.jooq.tables.TDemo.T_DEMO;

    /**
     * The table <code>test.t_fiance_temp</code>.
     */
    public final TFianceTemp T_FIANCE_TEMP = com.paulliu.jooq.tables.TFianceTemp.T_FIANCE_TEMP;

    /**
     * The table <code>test.t_other</code>.
     */
    public final TOther T_OTHER = com.paulliu.jooq.tables.TOther.T_OTHER;

    /**
     * 提现订单表
     */
    public final TWithdrawOrder_201803 T_WITHDRAW_ORDER_201803 = com.paulliu.jooq.tables.TWithdrawOrder_201803.T_WITHDRAW_ORDER_201803;

    /**
     * No further instances allowed
     */
    private Test() {
        super("test", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TBonuspackageInfo.T_BONUSPACKAGE_INFO,
            TCapitalControl.T_CAPITAL_CONTROL,
            TCapitalJobConfig.T_CAPITAL_JOB_CONFIG,
            TCapitalJobLog.T_CAPITAL_JOB_LOG,
            TDemo.T_DEMO,
            TFianceTemp.T_FIANCE_TEMP,
            TOther.T_OTHER,
            TWithdrawOrder_201803.T_WITHDRAW_ORDER_201803);
    }
}
